### ISSUE TITLE
can't change variable in area plot view

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#101]
When the plot view is opened the variable can't be changed.

code may need to be rolled back
probably introduced in  [V2.1.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.1.2)

**Comment by htmlboss** [comment]
Fixed in PR #103

**Comment by Jeffreydaw** [comment]
This was reintroduced in commit https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/commit/367669ccbb1a9f2bcf32aae119aa667cce061c61 and repatched in release [v2.2.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.2)
see #156
