### ISSUE TITLE
Issue with Variable Range not updating

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1021]
**Describe the bug**
When selecting any dataset from the drop down menu the default Min and Max do not change to what was defined in the datasetconfig.json file.

**To Reproduce**
Choose any dataset and when you click on the "Go" button the values stay the same -5 to 30. When the "Auto" button is selected and then the "Go" button the "Variable Range" changes to the actual data values found in the given dataset. 

**Expected behavior**
When changing the dataset dropdown menu it would be ideal if the Variable Range is updated to what is defined in the datasetconfig.json file or at least auto-scale to that found in the dataset so that the plot contains higher resolution of oceanographic features.

**Screenshots**

Dataset 01. GIOPS 10 day Forecast 3D - LatLon
![image](https://user-images.githubusercontent.com/44408505/171413446-f309d6f4-9e65-475f-95d5-6806f0d7ef3b.png)

Dataset 04. RIOPS hourly 3D - Polar Stereographic
![image](https://user-images.githubusercontent.com/44408505/171413608-8c6c6761-6741-4471-9f65-4ed99bd28821.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows, and Mac
 - Browser [e.g. chrome, safari] Chrome, Edge, Safari
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Android and iPhone
 - OS: [e.g. iOS8.1] N/A
 - Browser [e.g. stock browser, safari] Chrome, Edge, Safari
 - Version [e.g. 22] N/A

**Additional context**
N/A

**Comment by prodyut1978** [comment]
Variable range change only when change in variable selection. Same variable with different dataset example "Temperature " has the same range.

**Comment by JustinElms** [comment]
Fixed in #1088.
