### ISSUE TITLE
Profile Point Plot for CMEMS Dataset Showing Error When Plotting

### ISSUE THREAD

**Issue by prodyut1978** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1034]
**Describe the bug**
All CMEMS Dataset showing error in both frontend and backend when plotting profile point plot.

**To Reproduce**
1. Select any CMEMS Dataset from Main Map Selection.
2.  Draw a point in the map.
3. Plot the point 
![Capture](https://user-images.githubusercontent.com/80789651/177812858-f6bc201e-bab9-4574-8a92-b8054ea90443.PNG)

**Screenshots**
![Capture 1PNG](https://user-images.githubusercontent.com/80789651/177812045-04343660-131d-491d-8c6c-46a296486a25.PNG)
![Capture2](https://user-images.githubusercontent.com/80789651/177812055-78c35acd-ccc3-431b-bf7b-166548e16c53.PNG)
![Capture3](https://user-images.githubusercontent.com/80789651/177812074-c45c2c38-159d-4876-90d2-84abb3f55627.PNG)

**Comment by JustinElms** [comment]
@prodyut1978 The CMEMS datasets are in the process of being updated/re-indexed. I reassigned this issue to @dwayne-hart and he'll update it once the process is completed.

**Comment by JustinElms** [comment]
Fixed with update and addition of #1039.
