### ISSUE TITLE
Hovmöller fails, 502 bad gateway. sad computer race condition?

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#105]
After plotting a transect and selecting the "hovmöller" tab sometimes the sad computer png appairs, but other times the diagram loads correctly. 

When debugging using the _Inspect network_ option it can be seen the first request that is sent fails. the error is a 502 bad gateway error. The request does get re-sent and the second time it is successful and renders but the `sadcomputer.png` gets rendered as well. If the `sadcomputer.png` renders first then when the plot renders it replaces it. but if the plot gets rendered before the `sadcomputer.png` renders the `sadcomputer.png` replaces it.  
This looks like it could be a race condition problem. but there is no good need for the `sadcomputer.png` to be rendered here when the picture is going to load properly.

![transsect502badgatway](https://user-images.githubusercontent.com/11149030/31400932-d1876836-adcb-11e7-8aac-baa2921cc88d.png)
above is the loading sequence which ended up displaying the `sadcomputer.png`

![transsect200ok](https://user-images.githubusercontent.com/11149030/31401109-63725fda-adcc-11e7-8e62-d0e4117bcce7.png)
above is the loading sequence which ended up displaying the proper plot. 

present in version: v2.1.2

**Comment by Jeffreydaw** [comment]
The `sad-computer.png` only gets triggered when the '502 bad gateway' error (and probably other errors) occurs. when that happens the state changed in the [StatsTable.jsx](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/master/oceannavigator/frontend/src/components/StatsTable.jsx) file causing line
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/92078e54079d2be5d85b4bc80e89550075701451/oceannavigator/frontend/src/components/StatsTable.jsx#L98
to be trigged. This renders the `fail` image. My guess is that this is not rechecked at any point to see if the proper image was loaded on a later attempt.  


Below is an example of the network requests when the initial request does not fail. as can be seen, there is no request sent for the `sad-computer.png`
![selection_057](https://user-images.githubusercontent.com/11149030/31631700-10c81860-b295-11e7-81ed-e05b98fcbac7.png)

**Comment by htmlboss** [comment]
Might want to check the python code that sends the request. The failed state is set if the ajax call fails.

`
 $.ajax({
      url: "/stats/",
      data: paramString,
      method: (paramString.length < 1536) ? "GET" : "POST",
      dataType: "json",
      cache: true,
      success: function(data) {
        this.setState({
          data: data,
          fail: false,
          loading: false,
        });
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(url, status, err.toString());
        this.setState({
          loading: false,
          fail: true,
        });
      }.bind(this)
    });
`

**Comment by Jeffreydaw** [comment]
I have released a patch for this bug but that patch has created its own issue. 
The patch involved adding a check to see if a query fails twice instead of just once. This works but it means in in the cases where a second query (most of the time a second query seems to be sent) is not sent the loading wheel spins forever. 
Patch is in: 
#120 
[v2.1.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/releases/tag/v2.1.3)
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/831285b40001a1a592e25e5ed76061c9b6e76c39/oceannavigator/frontend/src/components/PlotImage.jsx#L69-L76
I have opened several related issues:
#118 
#121 
#122

Closing issue as patch works and other issues are open to addressing the other problems.

**Comment by Jeffreydaw** [comment]
Reopening because this "fix" only reduces the problem. It still happens to often even with this improvement.

**Comment by htmlboss** [comment]
Tentative fix in #206
