### ISSUE TITLE
Class 4 and Obs display overlap

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1058]
Selected/plotted Class 4 data. After the data was plotted I selected Observations and plotted obs in a specific area. The Class 4 data points remained when the Obs data was shown in the plot view. I would have expected the Class 4 data to be removed once I selected/plotted the Obs. Red dots are Observations and green/yellow/red are Class 4.
![image](https://user-images.githubusercontent.com/30048431/185690352-5c0c760d-ff93-47fb-b103-bc1a199a3475.png)
ervations.

**Comment by JustinElms** [comment]
Fixed in #1088.
