### ISSUE TITLE
side by side - point data

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#107]
when I compared point data for GIOPS and RIOPS daily average, selecting the point in either plot resulted in the GIOPS data in the CTD profile. (ie no comparison of the data sets) 

http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A2%2C%22scale%22%3A%220.0086%2C0.5935%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A555%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%2247.8752%2C%20-50.5656%22%5D%2C%22point%22%3A%5B%5B47.87519262186774%2C-50.565614948770396%5D%5D%2C%22center%22%3A%5B%22-50.1631%22%2C%2249.4175%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22world%22%2C%22zoom%22%3A7%2C%22dataset%22%3A%22giops_day%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A579%7D

**Comment by htmlboss** [comment]
Unfortunately, this was one of the side by side features I wanted to implement, but didnt have enough time for. I'll start work on this as soon as I finish the subsetting feature for DND (soon hopefully). Bottom line: it's on my radar now and I'll schedule it in asap.
