### ISSUE TITLE
Class 4 data not displaying properly

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1072]
The drop down menu for the Class 4 data is populated, however, the data does not populate. Below is the error message received. 

![image](https://user-images.githubusercontent.com/30048431/197270687-d9ed3879-81e0-462c-bf26-76660e64a531.png)

**Comment by JustinElms** [comment]
The `CLASS4_FNAME_PATTERN` config variable wasn't updated on production. Looks to be working as expected after updating the variable and restarting the service.
