### ISSUE TITLE
side by side - difference in variable range set and displayed

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#108]
The ranges for the two datasets are set to be the same,however, are different in the plots.

http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%220.0086%2C0.5935%22%2C%22scale_1%22%3A%220.008580309324205344%2C0.593536827235331%22%2C%22scale_diff%22%3A%22-0.32%2C0.32%22%2C%22colormap%22%3A%22default%22%2C%22showmap%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22size%22%3A%2211x8.5%22%2C%22dpi%22%3A144%2C%22depth_limit%22%3Afalse%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22line%22%2C%22names%22%3A%5B%5D%2C%22line%22%3A%5B%5B%5B48.78090774206214%2C-52.63194719960396%5D%2C%5B49.74161888303618%2C-48.58897844960396%5D%5D%5D%2C%22center%22%3A%5B%22-50.1631%22%2C%2249.4175%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22world%22%2C%22zoom%22%3A7%2C%22dataset%22%3A%22giops_day%22%2C%22variable%22%3A%22vomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A579%7D

**Comment by htmlboss** [comment]
Hmm...the ranges are being sent to the server, seems like there's an issue in the range logic.
