### ISSUE TITLE
area plots not displaying for side by side 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#110]
in the side by side view, only the difference plot is being displayed. the individual plots are not. 

noticed on Oct 12 and was working on the 11th (we think) 
in version v2.1.2

**Comment by htmlboss** [comment]
Basically the area plotter needs to be completely refactored to support multiple maps, otw there will be some nasty code duplication (like ~3000 lines).

**Comment by Jeffreydaw** [comment]
@htmlboss  wasn't this working at some point though?

**Comment by Jeffreydaw** [comment]
ok in that case I'll move it to the icebox

**Comment by Jeffreydaw** [comment]
dependent on #294
