### ISSUE TITLE
observations, model line no longer plotted 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#113]
On the production server when plotting an observation the model line no longer appears in the plot. 
for example under points>observations select Hutson 116 then select point 036 the result on Dory and Trinity can be seen below. 
 
![observationplotdory](https://user-images.githubusercontent.com/11149030/31614635-9c8b4784-b261-11e7-862f-8d23c98be3dc.png)
Dory ^

![observationplottrinity](https://user-images.githubusercontent.com/11149030/31614638-9e164e8c-b261-11e7-9cb3-80d48c683e29.png)
Trinity ^

this bug was first noticed in version: [v2.1.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.1.2)

**Comment by htmlboss** [comment]
Might want to compare the observation.py files on both servers to see if I accidentally deleted something. I don't recall changing that file tho...

**Comment by Jeffreydaw** [comment]
@VanessaSutton-Pande flagged that the graph that is plotted also has another problem. The title states the date, but not the date it should be plotting. the date it plots is the date which was in the map view. 

It looks like the line that is plotted on Dory is the model, not the observation (python probably defaults to blue as the colure of the first line)

**Comment by Jeffreydaw** [comment]
I tried rolling back to several past versions of the code including #78, https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/commit/0d31b491164691194aa8bb8497a2e7bdcf6470c0 and the first version with a UI https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/commit/add4b0f559fcaf4e1c54f97e418b68e9ecd677ac  

none of them had the line plotter like it is on Trinity, I also tried to point the data source to Trinity. with the same results. finally, I used a new version of the code that is running on Trinity and ran that but that still did not yield results. I can only conclude the version on trinity has a difference that has never been committed to this git responsory. 

TODO: run a diff on the files on Trinity compared to our files actually the [observation.py ]( https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/master/plotting/observation.py ) file 

this bug seems to have been present on dory forever.

**Comment by htmlboss** [comment]
There now appears to be a missing function `self.subtract_climatology` that appears to never have been included in git. Dory seems to have it and so does Trinity, but it's not on git...so the mooring tab is broken on any other machines. I'll tackle this.

**Comment by Jeffreydaw** [comment]
I forgot to update this but my test of rolling the code back is invalid. I messed up when I did it and forgot up rebuild the javascript after rolling back.

**Comment by htmlboss** [comment]
So I found the missing function...and it's creating more object attributes that are missing on the git version. I'll try to resolve this nonsense next week (hopefully the plot too).

**Comment by Jeffreydaw** [comment]
where did you find it? on trinity ?

**Comment by htmlboss** [comment]
ye. `/srv/etc`

**Comment by Jeffreydaw** [comment]
Is there an update on this? fraser would like this bumped up in priority
