### ISSUE TITLE
Mysterious dialog appears after loading a link created by "Get Link"

### ISSUE THREAD

**Issue by Aroweeri** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1131]
**Describe the bug**
When opening Ocean Navigator via a link created from the "Get Link" window, a blank dialog is shown. No information is presented, just a close button:

![image](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/assets/22351411/2fbc2abb-11cf-427b-8554-e384798d7965)

**To Reproduce**
Open Ocean Navigator
Click on "Get Link"
Copy/Paste the link into a new tab
Notice the empty dialog that appears when the page loads.

Below is an example link with this behavior:

https://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3Anull%2C%22showModal%22%3Atrue%2C%22modalType%22%3A%22%22%2C%22names%22%3A%5B%5D%2C%22vectorId%22%3Anull%2C%22vectorType%22%3A%22point%22%2C%22vectorCoordinates%22%3A%5B%5D%2C%22selectedCoordinates%22%3A%5B%5D%2C%22dataset0%22%3A%7B%22id%22%3A%22giops_day%22%2C%22model_class%22%3A%22Mercator%22%2C%22quantum%22%3A%22day%22%2C%22time%22%3A2342995200%2C%22depth%22%3A0%2C%22starttime%22%3A2341267200%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22variable_range%22%3A%7B%22votemper%22%3Anull%7D%2C%22quiverVariable%22%3A%22None%22%2C%22quiverDensity%22%3A0%2C%22default_location%22%3Anull%7D%2C%22mapSettings%22%3A%7B%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22extent%22%3A%5B%5D%2C%22interpType%22%3A%22gaussian%22%2C%22interpRadius%22%3A25%2C%22interpNeighbours%22%3A10%2C%22mapBathymetryOpacity%22%3A0.75%2C%22topoShadedRelief%22%3Afalse%2C%22bathymetry%22%3Atrue%2C%22bathyContour%22%3A%22etopo1%22%7D%7D

**Expected behavior**
No dialog appears! Or if one appears, have it say something!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 122.0.6261.129

**Comment by JustinElms** [comment]
Thanks for the feedback Dylan! It looks like some of these Get Link feature issues were fixed in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/pull/1116 and should be resolved once we push 9.2 this week. If you spot any other issues please let us know!
