### ISSUE TITLE
"Get Link" window's close button has "Close Close" as the label.

### ISSUE THREAD

**Issue by Aroweeri** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#1132]
**Describe the bug**
A typo exists in the close button on the "Get Link" window:

![image](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/assets/22351411/5fa47f60-e5eb-4850-b499-89563b7f0b3a)

**To Reproduce**

Open the "Get Link" window

**Expected behavior**
The label should read "Close"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 122.0.6261.129

**Comment by JustinElms** [comment]
Fixed in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/pull/1116
