### ISSUE TITLE
Plot load causes 502 Bad gateway

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#122]
The query that gets sent to request the data required to load the plot for a transect often returns with a 502 Bad gateway error. This has been at least in part the root cause of bug #105. while a patch has been implemented for that issue the root cause should be addressed which may allow for issue #105 to be rolled back. this would be good because the patch is a bit of a hack and causes its own issues. 
see issue #105 for some debugging information.

**Comment by htmlboss** [comment]
Tentative fix is now on dev #211
