### ISSUE TITLE
Version and document the API

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#133]
There has been some interest in having an API for the Navigator. Unfortunately, the current API has some changes that are needed to fix some bugs and add new features. To solve this problem we should implement a version system on the API so that each change has a version associated with it, independent of the code version numbers.

we will need to decide how many versions back we will want to support especially in the case that  API is found to provide incorrect information.

**Comment by Jeffreydaw** [comment]
**Critical!!!:** if updating the API make sure to check the regex expressions in the Nginx caches. This is critical or the navigator may display old information.  Particularly for the 10-day forecasts.  See issue #66

**Comment by Jeffreydaw** [comment]
some versioning has been added in release [v2.3.0](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.0)

**Comment by Jeffreydaw** [comment]
it may be worth looking at this api style as a guide, I like the fact that it can build some of the queries for you.
https://olympicsapi.docs.apiary.io/#reference/olympics/list-all-medals-by-rank

**Comment by NoahGallant-MUN** [comment]
I think this has been done.
I will create a new issue to update the api documentation with new changes
