### ISSUE TITLE
Subset to NetCDF3 actually exports NetCDF4

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#135]
NetCDF subsetting tool in development provides the option to export to NetCDF3 or NetCDF4. The file that is exported is named with the correct option. However, when inspected with a NetCDF viewer, the file type is "Hierarchical Data Format, version 5" (aka NetCDF4) regardless of selecting NetCDF3 or NetCDF4.

**Comment by htmlboss** [comment]
Fixed.
