### ISSUE TITLE
Dateline transect thumbnail

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#137]
weird behavior happens when plotting lines across the dateline

line drawn
![selection_089](https://user-images.githubusercontent.com/11149030/32448960-e5468490-c2ea-11e7-9b1b-182a989f6999.png)

resulted plot line path 
![selection_088](https://user-images.githubusercontent.com/11149030/32448892-b8c6c51a-c2ea-11e7-84f6-b9719aa7ca38.png)

[here is an example plot](http://navigator.oceansdata.ca/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22colormap%22%3A%22default%22%2C%22showmap%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A144%2C%22depth_limit%22%3Afalse%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22line%22%2C%22names%22%3A%5B%5D%2C%22line%22%3A%5B%5B%5B2.4182114956262524%2C-132.19910224693243%5D%2C%5B-12.848322762945045%2C-106.33894745443246%5D%2C%5B-29.702036598010125%2C-142.68294878443237%5D%2C%5B-43.64325958218505%2C-118.91956329943241%5D%2C%5B-12.848322762945045%2C-198.5967969844324%5D%2C%5B-36.711372293431765%2C-229.34941349443244%5D%5D%5D%2C%22center%22%3A%5B%22-155.2308%22%2C%2274.8628%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22zoom%22%3A1.008647456281032%2C%22dataset%22%3A%22giops_day%22%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A605%7D) and [here is a link showing what order the points were ploted in](https://www.mapcustomizer.com/map/OceanNavigatorTransectExample1).  The points are ploted in the same order asn the URL query is sent in. 

The order and number of points ploted do mot line up. 

It can be seen it the plot that the there are refferences to 180 deg west and 180 deg east, this is probably related. 

related to bug #130 
found  in release [v2.1.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.1.3) but probably has allways been a problem.

**Comment by Jeffreydaw** [comment]
note this issue does not affect the actual plot, Just the side image.

**Comment by Jeffreydaw** [comment]
Since this no longer shows incorrect information this is a very unimportant issue.

**Comment by Jeffreydaw** [comment]
though I am able to recreate this it is not easy, it would be weird for someone to encounter this issue Therefor I'm moving this to the icebox.

**Comment by htmlboss** [comment]
Unreported edge case. We can re-open this if needed in the future. Just trying to clean up and prioritise open issues.
