### ISSUE TITLE
add fvcom Bay of Funday

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#138]
Add fvcom dataset from the Bay of Funday added to the navigator.

**Comment by Jeffreydaw** [comment]
Because of the small size of some of their datasets, I have my doubts that it will be useful in the navigator until bug #7 is fixed and possibility bug #45 another layer of zoom might have to be added to allow for the dataset to be seen well as the provided plot is only about one-third of a tile in size at max zoom.  
![bayoffunoverlay](https://user-images.githubusercontent.com/11149030/32608422-e02c7f8e-c536-11e7-9435-c2d042d7a707.png)


![selection_092](https://user-images.githubusercontent.com/11149030/32608380-c2457aa2-c536-11e7-8a44-b5db7a117068.png)

**Comment by Jeffreydaw** [comment]
this issue is put on hold until we fix the other mentioned issues

**Comment by htmlboss** [comment]
FVCOM demo enabled in v3.2.1
