### ISSUE TITLE
Pre-compute Drifter model line

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#148]
Plotting drifters can take a long time for drifters that have been out for a long time. This is in part because a new file needs to be open for each date in the date range. 

To speed this up all the data for that track can be added to a fil for that drifter so only one file needs to be opened.

**Comment by Jeffreydaw** [comment]
This update is going to require a lot of changes to the drifter code. because of this and the planned change from IMEI to WMO (#161) in preparation for the new FTP site (#166) This issue is being put on hold until those issues can be dealt with.

**Comment by Jeffreydaw** [comment]
This may never be implemented. 
after further discussion, it seems that there may be a different issue causing the drifters to be slow. The issue was thought to be that the number of files that had to be open was what took so long. as it turns out it that may not be the bottleneck. Instead, it may be that for each file that is opened all the points in the area of the entire plot are requested. all that should be requested are the points near the place the drifter was on that day.

**Comment by htmlboss** [comment]
Not pursuing this since the storage requirements are not feasible and doesn't really feel like the correct course of action.
