### ISSUE TITLE
can't plot area plots other than temperature 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#156]
there has been a bug introduced between commit ce1de0eb47949695d7d259200732434adcde47f2  and commit  0fe852e2e5520363c933ccdd7656f2cff08260fe
it is now impossible to do an are plot for anything other than tempture, even if another varibale is selected.

**Comment by Jeffreydaw** [comment]
the bug was introduced in commit 367669ccbb1a9f2bcf32aae119aa667cce061c61

**Comment by Jeffreydaw** [comment]
The bug was conclusive introduced when line https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/6fe75300f788b3e1e772f2e968baee003c86600e/oceannavigator/frontend/src/components/OceanNavigator.jsx#L471

was removed from the code. in commit 367669c

**Comment by htmlboss** [comment]
Try changing line 491 in AreaWindow.jsx from `plot_query.variable = this.props.dataset_1.variable;` to `plot_query.variable = this.props.dataset_0.variable;`

**Comment by Jeffreydaw** [comment]
@htmlboss yes that does fix the problem. I had found a fix but it meant undoing some of the things you had done.

**Comment by Jeffreydaw** [comment]
fixed in version [v2.2.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.2)
