### ISSUE TITLE
reenter colour scale selection. 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#160]
There used to be a feature that allowed the user put change the color scale if they wanted. this feature is no longer in the navigator. It should be re-added. It is useful for both colour blind people and for a presentation where the projector or wall color can mess with the colors.  

noticed this was missing in version  [v2.2.1](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.1) but probably missing before that.

**Comment by htmlboss** [comment]
Oh yah I remember removing that for some reason, and forgot to re-add it. I'll look into this.

**Comment by htmlboss** [comment]
Done. See connected PR.

**Comment by Jeffreydaw** [comment]
fixed in release [v2.2.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.3)
