### ISSUE TITLE
Grid lines stop at International Dateline

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#164]
the grid lines stop at the International Dateline
see example [here](http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22178.2107%22%2C%2240.2323%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A4%2C%22dataset%22%3A%22giops_month%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A679%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A20%7D)
![selection_087](https://user-images.githubusercontent.com/11149030/34997952-5d7fe9e2-fab8-11e7-916d-6854bac4f4c7.png)

related to issue #130 
known to be present in verson v2.1.3 and still presten in v2.2.2

**Comment by htmlboss** [comment]
This is a OpenLayers issue. Since this has not been reported by users I'll go ahead and close this up. We can re-visit this if needed.
