### ISSUE TITLE
Investigate why RIOPS is slow

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#171]
Today after restarting the thredds server I noticed that the RIOPS monthly was loading as fast as the GIOPS, while the RIOPS (the 3 hour one) took a long time to load as it has for quite some time, almost 2 minutes, to load [this](http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22-44.2794%22%2C%2242.6523%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A5%2C%22dataset%22%3A%22riops%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A685%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A3170%7D).  I think that the long load time must not be because RIOPS is so high resulation bure instead it has somthing to do with how the files are stored and how thredds accesses them.  

Notably on the test server (which has fewer files) the  load time was just over a minuent.

**Comment by Jeffreydaw** [comment]
One reason for RIOPS being slow seems to be that when RIOPS is selected requests being for a time index that is not the correct one. 
When RIOPS is selected a process begins to calculate the needed time index. But before that can finish, requests for an incorrect time index gets sent. This means that RIOPS has to wait twice as long as is necessary since a full page of RIOPS that is never rendered gets requested.

**Comment by Jeffreydaw** [comment]
@htmlboss you thought you knew where this code was. could you post it here?

**Comment by Jeffreydaw** [comment]
looking into the aggregated.ncml that are in the thredds cache it seems that there are some that don't have time stamps for the cache, this probably means that for some reason the files are not being cached.

**Comment by nsoontie** [comment]
Another hint, the thredds server needs to load the entire dataset in order to define the time indices. This can be quite slow with large datasets.
See https://www.unidata.ucar.edu/software/thredds/v4.6/netcdf-java/ncml/Aggregation.html#joinExisting
(Specify number of coordinates section)

**Comment by Jeffreydaw** [comment]
some more information about current state. 

test server RIOPS time to lode all tiles: 2m 25s 
test server RIOPS date range: July 2016 to Feb 2018
test server total number of files:  9774

production server RIOPS time to lode all tiles: 6m 40s 
TTFT time to first tile: 2m 6s
production server RIOPS date range: 2016/06/01 to 2018/07/24
production server total number of files:  14062

production server RIOPS (not cached) monthly time to lode all tiles: 1m 40s 
TTFT time to first tile: 1m 2s
production server RIOPS date range: 2016/06 to 2018/06
production server total number of files:  56

production server RIOPS (cached) monthly time to lode all tiles: 16s 
TTFT time to first tile: 5
production server RIOPS date range: 2016/06 to 2018/06
production server total number of files:  56

production server GIOPS monthly time to lode all tiles: 15s 
TTFT time to first tile: 3
production server GIOPS date range: 2016/06 to 2018/06
production server total number of files:  38


**all right now for what we think we know.** 

- The data only seems to be slow down with some datasets (mainly RIOPS)
- The RIOPS Monthly dataset seems unaffected by the slow down and the RIOPS daily dose not seem to be affected much. 
- - therfore it's probably not the resulation of the data or other data type problem. 
- GIOPS monthly is much fater than RIOPS monthly when the tiles are **not** cached but are about the same speed for the cached. this indecates that the tiles do take longer to generate for the higer res RIOPS but again that is not the main cause of RIOPS taking so long (>6m) 
- adding the rotation files caused a notable slowdown.
- - attempting to fix the rotation grid involved 2 notable thing
- -  1. dubbling the number of files
- -  2. the addtion of more scan blocks to the uion blocks, scaning subfolders, and the first addition of Uion to the GIOPS aggreation. 
- - both GIOPS and RIOPS Slowed down much more than before. RIOPS took about 5 min for TTFT while GIOPS loaded fasted but was still slower than it was before. 

- there is some information to imply tht union dose no cach 
- - 
- -https://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#AggregationCache



**conclusion**
 There are 3 possible causes of the problem. 
1. too many file mangaged by one aggration
2. too many files in one folder 
3. uion dose not cach  (see: https://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#AggregationCache) 
there is also some chanch that it has to do with the number of open files that THREDDS has but I have not looked into that aspect.

**Comment by Jeffreydaw** [comment]
Testing with aggreation file that is just RIOPS 3D for 2017

tiles cased on the server loaded right away but only when the union was removed when the union was still in place even though it should not have been unioning anything it still took 1min to load. 

clearly, the Union is causing some problems.

**Comment by Jeffreydaw** [comment]
testing local on my computer with data on dory. 
format, files are all in the same place they have always been. but 2 new aggregation files have been added. aggregated_2d.ncml , and aggregated_3d.ncml that look at the same files but look for 2d or 3d files. 

RIOPS:
22min

RIOPS 2d only: 

RIOPS 3d only:
10 min

**Comment by htmlboss** [comment]
THREDDS has been dumped for some time now in favor of the index tool and we do not experience any performance issues with RIOPS now.
