### ISSUE TITLE
Water Velocity Virtual Morning Export Incomplete

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#172]
@VanessaSutton-Pande  noticed today that there is a bug in the .csv export for point plotting.  

Recreation: 
* Point -> draw on map
* Drop a point
* In the popup windeow select "virtual morning" 
* select "water velocity"
* Save As -> csv 

Result:
The exported file outputs "Water X Velocity (m/s)" but does not export "Water Y Velocity (m/s)"

Expected Result:
 We should derive the net water velocity and bearing like we do for the area plots. Or at the very least export x and y velocity. 

[example point](http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A7%2C%22scale%22%3A%22-1.0222365856170654%2C1.1149781942367554%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A408%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%5D%2C%22point%22%3A%5B%5B45.5368%2C-48.593049991023214%5D%5D%2C%22center%22%3A%5B%22-48.5137%22%2C%2244.9178%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A7%2C%22dataset%22%3A%22riops_daily%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A686%7D%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A468%7D)

First noticed in release: [v2.2.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.2)

**Comment by clydeclements** [comment]
Fixed in commit 0f9d17a.

**Comment by clydeclements** [comment]
CSV export for the stick plot now includes X and Y velocity components and bearing information; see commit 1819bf0.

This now matches what happens for CSV export of water velocity in the virtual mooring and area map cases. Are there other places this capability should be included?

**Comment by clydeclements** [comment]
I've just added a minor change (commit 0cca73f) to adjust the order of exported variables for a stick plot so that it matches the virtual mooring export, as requested by @VanessaSutton-Pande.

**Comment by Jeffreydaw** [comment]
fixed in release [v2.2.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.3)
