### ISSUE TITLE
csv line upload broken

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#174]
When a user tried to upload a CSV, it just plots a bunch of points instead of lines. 
The upload works fine on Trinity. 

also, the enter corrodents option does not work for line selection either though that may be a separate bug. 
@htmlboss any Ideas?

**Comment by htmlboss** [comment]
Pretty sure they're separate. I'll need a sample csv to see what's up.

**Comment by Jeffreydaw** [comment]
This is still an issue as of version v2.3.2. 

sample csv:

> latitude, longitude 
> 45.555, -55,555
> 40.666, -50,999

**Comment by jamesprayner** [comment]
fix in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/pull/366
