### ISSUE TITLE
Toggling sidebar in compare mode distorts maps

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#18]
Distortion can only be reset upon panning or zooming the map. Due to how OpenLayers does its rendering, its not really possible to "fix" this, unless sidebar toggling is disabled in compare mode, or another UI solution is discussed (maybe each map would get it's own floating/draggable toolbar).

**Comment by Jeffreydaw** [comment]
Is this fixed now? I don't seem to be able to replicate the problem.
