### ISSUE TITLE
Make Sound Profiles Narrow 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#180]
Sound profiles are typically less wide then the navigator displays. to be closer to standard practice we should make our more narrow as well. 
![old image](https://user-images.githubusercontent.com/11149030/35410443-07d39bb2-01f0-11e8-949b-1a13bba4c29a.png)

[example link](http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A5%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A664%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%2247.2327%2C%20-48.1007%22%5D%2C%22point%22%3A%5B%5B47.23272693335352%2C-48.100738525390625%5D%5D%2C%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A4%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A688%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A688%7D)

**Comment by clydeclements** [comment]
I have updated the plot so that it has a more narrow aspect (see commit f1fc2a7). Here is the new plot using the same data in the comment above:

![screenshot from 2018-01-26 13-10-29](https://user-images.githubusercontent.com/13748047/35451583-4e57e2ec-029e-11e8-9828-e303dfc98d93.png)

**Comment by Jeffreydaw** [comment]
implemented in release [v2.2.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.3)
