### ISSUE TITLE
Inconsistent depth value in CSV export for time series

### ISSUE THREAD

**Issue by clydeclements** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#181]
The depth value shown in the header of the CSV export for a time series (or virtual mooring) does not consistently match the value selected in the user interface. The problem was found using the GIOPS Daily dataset.

To recreate this problem:
* Select Point, then Draw on Map.
* Drop a point.
* In the pop-up window, select Virtual Mooring.
* Select the variable temperature and a depth of 2 m.
* Select Save as CSV.

The CSV file will contain the following header line:
```
// Depth: 1
```
Note this depth value does not match the 2 m selected in the interface.

**Comment by clydeclements** [comment]
Fixed in commit 26f9409.

**Comment by Jeffreydaw** [comment]
fixed in release [v2.2.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.3)
