### ISSUE TITLE
Virtual mooring CSV export for water velocity has wrong column label

### ISSUE THREAD

**Issue by clydeclements** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#183]
To recreate this problem:
* Select Point, then Draw on Map.
* Drop a point.
* In the pop-up window, select Virtual Mooring.
* Select the variable Water Velocity.
* Select Save as CSV.

The CSV file will have the velocity column labelled *Water X Velocity*, not the expected *Water Velocity*. The exported values are indeed the water velocity (i.e., the magnitude of the X and Y components), it's just the wrong label for the column.

**Comment by clydeclements** [comment]
Fixed in commit 0eb6ae3.

**Comment by Jeffreydaw** [comment]
fixed in release [v2.2.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.3)
