### ISSUE TITLE
Add Option To Change The Title Of Plots

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#184]
Some users would like the ability to change the title of plots before they are downloaded. Maybe we could provide a popup with options when download is selected?

**Comment by htmlboss** [comment]
Is this applicable to all the plotting features we have? Like sticks, transects, area, etc?

**Comment by Jeffreydaw** [comment]
@htmlboss , yes I think the Idea is to rename any plot. I think we would only need to do this for downloads though. I don't see a huge advantage to changing the plot names in the navigator its self. I would also probably assume the default title unless the user decides to rename.

**Comment by htmlboss** [comment]
It really makes no difference if we only change the saved image vs whats displayed on the navigator. We send the same query anyways. Ill write it so the navigator gets the change and we can see from there.

**Comment by NoahGallant-MUN** [comment]
Fixed in #250
