### ISSUE TITLE
Add user selection of profile depth range

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#185]
Users would like the option to select the depth range on the profiles. 

this affects several tabs when ploting a point including: [profile](http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A665%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%2244.6043%2C%20-50.3859%22%5D%2C%22point%22%3A%5B%5B44.60426450121511%2C-50.38589477539062%5D%5D%2C%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A4%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A689%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A689%7D), [CTD Profile](http://navigator.oceansdata.ca/?query=%7B%22subquery%22%3A%7B%22selected%22%3A2%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A665%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%2244.6043%2C%20-50.3859%22%5D%2C%22point%22%3A%5B%5B44.60426450121511%2C-50.38589477539062%5D%5D%2C%22center%22%3A%5B%22-50.3859%22%2C%2244.6043%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A689%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A689%7D), And the [Sound Speed Profile](http://navigator.oceansdata.ca/?query=%7B%22subquery%22%3A%7B%22selected%22%3A5%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22depth%22%3A0%2C%22colormap%22%3A%22default%22%2C%22starttime%22%3A665%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22point%22%2C%22names%22%3A%5B%2244.6043%2C%20-50.3859%22%5D%2C%22point%22%3A%5B%5B44.60426450121511%2C-50.38589477539062%5D%5D%2C%22center%22%3A%5B%22-50.3859%22%2C%2244.6043%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A689%7D%2C%22variable%22%3A%22votemper%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A689%7D)

Related to #180

Its has also been suggested that this feature is added to the transects; see issue: Add user selection of transect depth range #186

**Comment by NoahGallant-MUN** [comment]
Implemented in new User Interface

**Comment by NoahGallant-MUN** [comment]
Also part of issue #326
