### ISSUE TITLE
Linear Threshold Selection Misbehaving 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#187]
After plotting a transect the users has the option to change the Linear Threshold (the dotted line which shows the change form a linear to logarithmic scale). the problem is that if the user starts typing in the box the requests start going through right away. This means that a requests get sent for unneeded values which sometimes get displayed.  Also when the user hits enter whatever they have typed disrepair's.  

Possible fix: require enter to be pressed before the request gets sent. (and don't clear the line when enter is pressed)

**Comment by htmlboss** [comment]
This also applies to depth limit and any variable range boxes too.

**Comment by htmlboss** [comment]
Instead of 200ms timeout until the number box updates itself, I changed it to 1.25 sec.

**Comment by htmlboss** [comment]
fix is in interpolation branch.
