### ISSUE TITLE
Remove unnecessary requests

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#189]
There are several places in the code where images get requested that are not needed or used. This slows down the navigator. add such issues to this epic.

**Comment by htmlboss** [comment]
Started re-jigging all of the components to hopefully reduce the number of updates being done. I'll probably uncover some issues as I go along.

**Comment by htmlboss** [comment]
Noah did some poking around and my initial idea about "conditional" rendering was totally wrong lol. Anyways we got a solution for this so he'll propagate it through the javascript.

The duplicate requests were coming from hidden dataset selectors for the comparison feature.

**Comment by NoahGallant-MUN** [comment]
Fixed the issue for the main, line, and area pages
