### ISSUE TITLE
multiple profile requests. 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#190]
When a request gets sent for the plot of a user drawn profile 3 images come back, 2 are unused. this is a waist of resources

the order of the plots that were requested are

![redundentprofile1](https://user-images.githubusercontent.com/11149030/35451448-d950e20a-029d-11e8-993f-7bd81d5aef77.png)
^ only one plot 

![redundentprofile2](https://user-images.githubusercontent.com/11149030/35451449-da7d843a-029d-11e8-805a-c6bb8c0c8d74.png)
^ two "(" in title

![redundentprofile3](https://user-images.githubusercontent.com/11149030/35451452-dcabb95c-029d-11e8-92a3-919fd0c9a93e.png)
^ correct image

this is true in the speed of sound profiles too. 
to be clear all the images do get shown but get replaced in a fraction of a second. 

These were found using the inspect elements developer tool.

**Comment by htmlboss** [comment]
This is related to how we issue ajax requests. I think we may need to wrap them into cancel-able objects so we can stop extraneous requests.

**Comment by htmlboss** [comment]
Noah and I managed to knock out some instances of other situations like this happening. I changed the default tab to Profile a while ago, so this bug is slightly mitigated.

**Comment by NoahGallant-MUN** [comment]
I think I mitigated this completely by requiring that you use the update button when changing variables.
This moves the update of the plot to a function, rather than updating automatically when the page is rendered.

~commit: 1a6071
