### ISSUE TITLE
Profile Fails

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#191]
Recreation:
* select velocity variable  
* point -> draw on map
* select the "Profile" tab in the popup window.  
* the sad computer png will appear as a result of a 502 Bad Gateway error

More information can be seen if using the inspect elements tool when running locally. 

This will happen for any variable that is a little odd such as the derived product "velocity" or any of the variables that are only one layer such as "sea surface height"

**Comment by htmlboss** [comment]
I've added an error message that will explain what's going on to the user and prompts them to select another variable. I don't see any other cleaner way of fixing this.
