### ISSUE TITLE
compare area plots not working

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#195]
when plotting in compare mode no area plots appear, just the sad compute png as a result of a 502 error. 

Replication steps:
* Select "Compare Datasets"
* Then select an area and create a plot. 
* The sad computer image will appear. 

The inspect elements tools will show that the 502 error does appear.  But unlike issue #105 a second request does not get sent.  
there seems to have been a bug introduced between commit a5698ce81e29f2af816a264fb23e0211f5f1a77d and commit 0987753  ([version 2.2.4](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.4)).

Bug discovered in ([version 2.2.4](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.4))

**Comment by Jeffreydaw** [comment]
This bug was introduced in commit 6d3788961991e78b45d9ba52a69a27ee21f8689d that commit contined a fix for issue #160 (reenter colour scale selection)

**Comment by Jeffreydaw** [comment]
@htmlboss maybe you could take a look at this?

**Comment by htmlboss** [comment]
I never actually had the chance to finish that feature because of the necessity of that refactor I was telling you about. Ill see what's causing the error tho.

**Comment by Jeffreydaw** [comment]
@htmlboss yeah, I remember you saying that, and that's why we would not see the left or right views plotted. But before the 6d37889 commit difference plots would be created, now they fail too.

**Comment by Jeffreydaw** [comment]
the quick fix for this is in release [v2.2.5](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.2.5)
