### ISSUE TITLE
Drifter window view is broken

### ISSUE THREAD

**Issue by Ocean-Navigator** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#2]
Some drifters provide the sad computer PNG when pressed. No pattern to which are broken has been found. 
example: [Drifter 300234063614000](http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22zoom%22%3A4%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%5B-5%2C30%5D%2C%22vectortype%22%3A%22drifters%22%2C%22vectorid%22%3A%22all%22%2C%22subquery%22%3A%7B%22showmap%22%3Atrue%2C%22variable%22%3A%5B%22votemper%22%5D%2C%22latlon%22%3Afalse%2C%22buoyvariable%22%3A%5B%22sst%22%5D%2C%22starttime%22%3A%222015-11-05T18%3A30%3A16.000Z%22%2C%22endtime%22%3A%222017-07-07T13%3A29%3A12.000Z%22%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A72%2C%22depth%22%3A0%2C%22mindate%22%3A%222015-11-05T18%3A30%3A16.000Z%22%2C%22maxdate%22%3A%222017-07-07T13%3A29%3A12.000Z%22%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22drifter%22%2C%22names%22%3A%5B%22300234063614000%22%5D%2C%22drifter%22%3A%5B%22300234063614000%22%5D%7D)

**Comment by VanessaSutton-Pande** [comment]
Drifter 300234063260870 opened correctly and then the sad computer PNG appeared

**Comment by htmlboss** [comment]
Confirmed 504 timeout. Cause still unknown. Python?

**Comment by Jeffreydaw** [comment]
This is fixed thanks to the correction to the Nginx timeout. See issue #218
