### ISSUE TITLE
Python 3 port.

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#201]
Steps to create a minimal Python 3.6 environment for the navigator. This is being updated as I work:

* `conda create -n python36 python=3.6`
* `source activate python36`
* `conda install gdal` <-- DO NOT install from conda-forge cuz it will mess everything up idk why.
* `conda install -c conda-forge flask-compress`
* `conda install -c conda-forge flask-babel`
* `ConfigParser` has been renamed to `configparser`.
* `conda install -c conda-forge pykdtree`
* `conda install -c conda-forge geopy`
* `conda install -c conda-forge pyresample`
* `conda install -c conda-forge matplotlib`
* `conda install -c conda-forge cachetools`
* `conda install -c conda-forge netcdf4`
* `conda install -c conda-forge basemap`
* `conda install -c conda-forge cmocean`
* Fixed StringIO import error
* `conda install -c conda-forge pint`
* `conda install c conda-forge pillow`
* `conda install -c conda-forge shapely`
* `conda install -c conda-forge pykml`
* Edit pykml parser.py (we need to add to our repo).
* `conda install lxml`
* `conda install libiconv`
* `conda install -c conda-forge thredds_crawler`
* `conda install -c conda-forge seawater`
* `conda install -c conda-forge scikit-image`
* `conda install -c conda-forge bottleneck`
* `conda install -c conda-forge xarray`
* `conda install -c conda-forge basemap-data-hires`

**Comment by htmlboss** [comment]
Package installations done. Now I need to upgrade our code for Python 3.6

**Comment by htmlboss** [comment]
Still fixing more crap.

**Comment by htmlboss** [comment]
Yah probably

**Comment by htmlboss** [comment]
I dont plan on opening more issues about this anyway until its ready for testing.

**Comment by htmlboss** [comment]
Main issue now is that no data is actually being loaded from the netcdf files, which is really weird. Nothing for tiles, or plots, or csv...

**Comment by Jeffreydaw** [comment]
Just thought I'd post this here unidata is planning on dropping support for Python 2.7 in 2019. All the more reason to move. 

https://www.unidata.ucar.edu/blogs/developer/en/entry/timeline-for-dropping-support-for
