### ISSUE TITLE
small Islands disappear

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#209]
![Screenshot from 2018-03-19 14-58-39.png](https://images.zenhubusercontent.com/595fa79661b4ca3b0a738fcc/3b9f3f5f-918c-4bf5-a1ff-930c823c29d5)

No Bell Island 

[mtplotlib resolution](https://matplotlib.org/basemap/api/basemap_api.html) may need to be changed from Intermediate (i) to high (h) in [basemap.py#L21-L37](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/1a5c2adfa92c45dc1ad4f744e0699becf6857f04/plotting/basemap.py#L21-L37
) this will slow down the process so we may only want to do it for areas that are  smaller than a certain size. 

            if projection in ['npstere', 'spstere']:
                basemap = Basemap(
                    resolution='i',
                    ellps='WGS84',
                    projection=projection,
                    boundinglat=center[0],
                    lon_0=center[1])
            elif projection == 'merc':
                basemap = Basemap(
                    resolution='i',
                    ellps='WGS84',
                    projection=projection,
                    llcrnrlat=height[0],
                    llcrnrlon=height[1],
                    urcrnrlat=width[0],
                    urcrnrlon=width[1],
                )

Noticed in release [v2.3.1](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.1)

**Comment by Jeffreydaw** [comment]
A test with running on my computer shows that increasing the resolution from Intermediate (i) to high (h) makes the plots take about twice as long. While increasing to full (f) it takes about 8 min. 

This means that this plot of the [Atlantic ocean](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B73.96045342616904%2C-85.91607498712366%5D%2C%5B-47.88413636896644%2C-74.71769832750574%5D%2C%5B-49.16466265116992%2C11.590895422494258%5D%2C%5B72.96992791891111%2C4.074550229389362%5D%2C%5B73.96045342616904%2C-85.91607498712366%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-37.1626%22%2C%2226.7989%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A762%2C%22output_format%22%3A%22NETCDF3_CLASSIC%22%2C%22output_starttime%22%3A762%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22none%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22selected%22%3A1%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22variable%22%3A%5Bnull%5D%2C%22zip%22%3Afalse%7D%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A2%7D) gose from takeing about 50 seconds to plot to about 110 secons to run (1 min 50 sec) but a small plot like this one of [bell island](http://http://navigator.oceansdata.ca//public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B47.73327170356137%2C-53.15403403994267%5D%2C%5B47.49082277845349%2C-53.15403403994267%5D%2C%5B47.37854407677884%2C-52.66713826222946%5D%2C%5B47.707215819748455%2C-52.434756186502696%5D%2C%5B47.863355683857094%2C-52.68373698192423%5D%2C%5B47.73327170356137%2C-53.15403403994267%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-52.6594%22%2C%2247.1984%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A762%2C%22output_format%22%3A%22NETCDF3_CLASSIC%22%2C%22output_starttime%22%3A762%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22none%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22selected%22%3A1%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22variable%22%3A%5Bnull%5D%2C%22zip%22%3Afalse%7D%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A7.98959982002698%7D) goes from taking 5 seconds to 10 seconds. 
![image](https://user-images.githubusercontent.com/11149030/38621746-102b1160-3d7c-11e8-94ca-b144a554c4c7.png)

![image](https://user-images.githubusercontent.com/11149030/38621622-cce9e61a-3d7b-11e8-995e-cabb571dbd02.png)
unfortanally only the close zoom benefates from this change as the farout view dose not create an image that is hige res enough to see the small details. 

At the higest resulation option, full (f), increases the time by 8 compaired to intermeaded (i). 
this plot of [bell island](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B47.70357162123099%2C-53.175174370105275%5D%2C%5B47.108739603802576%2C-52.906009331042775%5D%2C%5B47.325142433561126%2C-52.246829643542775%5D%2C%5B47.85123052811477%2C-52.510501518542775%5D%2C%5B47.70357162123099%2C-53.175174370105275%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-53.0961%22%2C%2247.6370%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A762%2C%22output_format%22%3A%22NETCDF3_CLASSIC%22%2C%22output_starttime%22%3A762%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22none%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22selected%22%3A1%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22variable%22%3A%5Bnull%5D%2C%22zip%22%3Afalse%7D%2C%22time%22%3A762%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A8%7D) took 40 seconds. While the plot of the alantic took 390 seconds ( 6 min 30 sec) . 
![image](https://user-images.githubusercontent.com/11149030/38622008-c4cbefae-3d7c-11e8-90ad-0ea124900fd8.png)



Below is a summary of the different options 
___________________________________________________________________________________

`resolution='i',
                    area_thresh=100,`  ~5 seconds 
![image](https://user-images.githubusercontent.com/11149030/38629934-0254c91e-3d90-11e8-93bd-0a5ba4ff4dac.png)

`resolution='i',
                    area_thresh=10,`  ~5 seconds 
![image](https://user-images.githubusercontent.com/11149030/38629872-d17de62c-3d8f-11e8-98a3-6c51b61c00c6.png)

`resolution='i',
                    area_thresh=1,`  ~5 seconds 
![image](https://user-images.githubusercontent.com/11149030/38629708-5bde6b76-3d8f-11e8-9dfa-99d51a53349f.png)


`resolution='h',
                    area_thresh=1,` ~10 seconds 
![image](https://user-images.githubusercontent.com/11149030/38629995-43c82094-3d90-11e8-822e-3ea536592e73.png)

`resolution='f',
                    area_thresh=1,`  ~40 seconds 
![image](https://user-images.githubusercontent.com/11149030/38630118-907460d8-3d90-11e8-8612-eb77422e3c9d.png)

@FraserO My thought is that we should set the `area_thresh=1` and keep the resolution as Intermediate (i)  `resolution='i'. Unless you wanted to suggest something else. 

Side note: This dose not have any inpact on the resulation of the transects even if they pass over land they work without this fix.

**Comment by Jeffreydaw** [comment]
So we will try to go for the approach of having this be area dependent. small areas will have full resolution. large areas will have crude resolution.

**Comment by FraserO** [comment]
Agreed
Fraser

**Comment by Jeffreydaw** [comment]
fixed in commits f79466438b12780bead00e9afbf6ab106ae916ab and 2570f7f6fdb7abe32ed522de1e00e8cd51db11de

**Comment by Jeffreydaw** [comment]
fixed in release [v2.3.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/releases/tag/v2.3.3)
