### ISSUE TITLE
coastline resolution

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#210]
As can be seen below the coastline is quite blocky. Increasing the resolution as suggested in issue #209 does not fix this problem. 
![Screenshot from 2018-03-19 14-58-39.png](https://images.zenhubusercontent.com/595fa79661b4ca3b0a738fcc/3b9f3f5f-918c-4bf5-a1ff-930c823c29d5)

Noticed in release [v2.3.1](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.1)
been present since first release.

**Comment by Jeffreydaw** [comment]
This seems to be a result of the plotting function. plots are made using basemap but the global view is made using open layers, it seems this is the cause of the difference. 


below is a tile made from the open layers of the same area. as can be seen it is dose not have the blocky coast line. 
![image](https://user-images.githubusercontent.com/11149030/39924338-e7899e1e-5501-11e8-80d4-a18ac78c018e.png)


the blocks that area appairing may be the resulte of a mask that basmap is applying.

**Comment by nsoontie** [comment]
I've noticed the same issue when making area plots of the salish sea data. (Dark gray blocks). But, it's not as bad if you're plotting below the surface.

My guess is [maskoceans](https://matplotlib.org/basemap/api/basemap_api.html#mpl_toolkits.basemap.maskoceans) is the culprit.
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/cd4c72330fc2e3cab0ca925a335b068470cc3b42/plotting/area_plot.py#L424-L443

maskoceans has options for higher resolution and a better grid. Default grid is 5 minutes, which is wuite course when zooming in on the coast. We could go up to 1.25 minutes but that wouldn't be great for higher zoom levels.

**Comment by NoahGallant-MUN** [comment]
Done, set the resolution to high and to 1.25min... Doesn't seem to be any performance effect on larger plots
