### ISSUE TITLE
Bearing and vector representation

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#213]
Most of the models record water velocity along model grid lines, however, the utilities we use for plotting vectors assume that velocities are in east and north directions. As a result, we have several issues:

* Quivers showing velocity vectors are incorrect
* Bearing calculation is incorrect

**Comment by Jeffreydaw** [comment]
error was thrown when rotating giops monthly 201607 

    ncap2: WARNING prs_cls::ncap_var_init(): Unable to find variable u_wind in /data/GIOPS/monthly/rotated/tmp_giops_201607_cardinal_velocity.nc or /data/GIOPS/monthly/rotated/tmp_giops_201607_cardinal_velocity.nc
    ncks: ERROR nco_xtr_mk() reports user-supplied variable name or regular expression nav_lon is not in and/or does not match contents of input file
    ncatted: Variable <wind_east_vel> was not found

**Comment by nsoontie** [comment]
Did the problem happen with any other files? If not, the errors point to a problem with the file.

I downloaded this file from thredds.
There are several issues
1. u_wind isn't in the file, but it appears in the output of ncdump -h which I use to determine if rotation on the variable u_wind is needed. It seems strange to me that a variable would be listed in the history but not part of the file... 
Suggested fix: Change this line to 
varx=$(ncdump -h $xvel_file)
varx=$(ncdump -h $xvel_file | grep -v history)
But, I would check that there is no problem with the file first.  
2. nav_lon and nav_lat don't exist in the file. This suggests to me there is an issue with the file. Why doesn't it contain the coordinate data? Did the monthly averagin finish as expected?

**Comment by Jeffreydaw** [comment]
attempts at using precalculated rotated vector files have stopped as there were many many issues cropping up. the new approach is going to be to calculate them on the fly. to aid in this we will get the rotation file from the service desk, they have the amount each vector need to be rotated in it.
