### ISSUE TITLE
Ice velocity rotation

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#214]
Scripts for rotating velocity need to be modified to include ice velocities.

**Comment by nsoontie** [comment]
Is it ok to have rotated ice velocities in a separate file from rotated ocean velocities.
Does wind need to be rotated as well?

**Comment by nsoontie** [comment]
Script will append rotated ice velocities to file with rotated ocean velocities.

**Comment by nsoontie** [comment]
Script added in this commit: f97d334beb968ce557456eaa137a04e4b35bb04d

Ice velocities added to vector_map in this commit: 9e5f8824518dfd1a736e2c8ce9eb69d4dcdddbfc

**Comment by nsoontie** [comment]
Also added wrapper scrips for riops.

Commit fb22b64368a6fdba4c12ec34fc86bac89eba742f

**Comment by htmlboss** [comment]
Now that the calculation layer has been written, we should see if it would take care of this issue.

**Comment by htmlboss** [comment]
Yup the calculation layer fixes this. :tada: 
#378
