### ISSUE TITLE
Quiver Key label

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#219]
The Quiver key label isn't appropriate when plotting quivers from east/north velocity.
In this case, the label is Water North Velocity.

**Comment by nsoontie** [comment]
Modification to [plotter.py](plotting/plotter.py)

Added east and north to regular expression substitution on line 335. This renders labels as Water Velocity or Ice Velocity etc.

Also, fixes column heading for Water Velocity when downloading vectors in csv.

Fixed in commit 48302f99c642d62096347ed649aa217864769f36

**Comment by nsoontie** [comment]
NOTE: For map plots with Arrows from Water Velocity, the csv outputs are
VARIABLE, Water Velocity East, Water Velocity North, Bearing

where VARIABLE is whatever was chosen in the Variable box of the Main Map dialogue.

This behaviour is not introduced with this change, rather it is there by design.

@Jeffreydaw

**Comment by NoahGallant-MUN** [comment]
Fixed... Nancy is waiting to merge into dev

**Comment by Jeffreydaw** [comment]
@NoahGallant-MUN was this change merged?

@nsoontie what is the current status of this considering that we had to roll the North/East velocity code back

**Comment by nsoontie** [comment]
It is fine,. I modified the regex search to include 'east' and 'north. I also matches 'x' and 'y' as before.

**Comment by Jeffreydaw** [comment]
@nsoontie so it is back to it's previous broken state. I'll remove it from the done pipeline

**Comment by nsoontie** [comment]
No, it is not broken. I think it can stay as done and be closed.
