### ISSUE TITLE
Plots and Transects are Broken. 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#223]
The merge #206  into dev is broken. 

The loading wheel never ends when plotting a transect, Hovmoller, or area plot. 

As such Dev branch cannot be rolled out until this is fixed or reverted.

**Comment by htmlboss** [comment]
I'm going to need to see some error messages because I won't be able to reproduce this on my machine

**Comment by htmlboss** [comment]
No issue after all, just some typos in a config file.
