### ISSUE TITLE
Time selector broken for RIOPS

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#227]
The time picker is broken in the new rollout. 

**In RIOPS:**  (and RIOPS forecast) 
The time dropdown is blank and can't be selected. 
![image](https://user-images.githubusercontent.com/11149030/38382528-c8e1817c-38e4-11e8-9893-70a637773cbc.png)

Also selecting the date brings up the calendar.  But selecting another date does not actually bring you to the data for that date and the calendar does not update. 

![image](https://user-images.githubusercontent.com/11149030/38383123-37b0d4bc-38e6-11e8-8ede-9582646120da.png)

Selecting the arrows does seem to work for switching the dataset date but this means it takes 8 clicks to move 1 day. 

@htmlboss any idea what may be causing this? 

Intruduced in version [v2.3.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.2)

**Comment by htmlboss** [comment]
No idea what's going on here. Makes no sense that giops works for changing the date and riops dont. I cant see anything in the code right now that could be causing this. 

I'll be in on Monday to figure this out.

**Comment by Jeffreydaw** [comment]
That does seem a logical place to look. But weirdly you did not make any changes to that section (according to the diff) I did try to revert the one line change you made to the [timepicker.jsx](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/09923f82d9336b5b40bf2062981a39c9691193fe/oceannavigator/frontend/src/components/TimePicker.jsx) file but it did not fix the issue.

**Comment by htmlboss** [comment]
Fixed. Check #228
