### ISSUE TITLE
Manual entry of coordinates not working for transects

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#229]
Manual entry of coordinates is no longer working for transects. It is still working for area plots and profiles. 

@htmlboss don't suppose you changed anything with this recently?

**Comment by htmlboss** [comment]
Inadvertently changed lol. Shouldn't be a big deal to fix.

**Comment by Jeffreydaw** [comment]
good, thought that might be what happened.

**Comment by htmlboss** [comment]
Also noticed 2 input modals were being stacked on each other...so I fixed that lol.

**Comment by htmlboss** [comment]
Fixed on dev.
