### ISSUE TITLE
move VECTOR_MAP to config file

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#231]
The VECTOR_MAP dictionary defined in oceannavigator/views.py should be defined in a config file. Since the list a vector pairs may change has new datasets are added it is not a good idea to have this hard coded.

**Comment by htmlboss** [comment]
With the new calculation layer, we should investigate whether we can remove this dictionary entirely and perform the adjustments by defining a variable equation in the datasetconfig

**Comment by htmlboss** [comment]
VECTOR_MAP has been deleted for some time now. We rely on the calculation layer and the definition of a variable in the dataset config file to create magnitude variables.
