### ISSUE TITLE
Landing page fails on IE and Chromium. 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#233]
The new landing page does not render properly on IE, Chromium, or . It does work on Microsoft Edge, Google Chrome, and Fire Fox or Opera but often renders poorly on the first attempt.  Not tested on Safari.

![landingpageerror](https://user-images.githubusercontent.com/11149030/38814956-5a61a466-416d-11e8-9cc2-12f28c9dbf92.PNG)

According to [Wikipedia](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) IE makes up ~11% of desktop browser users. And according to [statista.com](https://www.statista.com/statistics/499466/most-popular-mobile-browsers-in-canada-by-market-share/) it makes up ~6% of usage in Canada
![image](https://user-images.githubusercontent.com/11149030/38815157-d6496942-416d-11e8-88e6-797e912aeec1.png). 

Tested with Internet Explorer version 
![ie_version2](https://user-images.githubusercontent.com/11149030/38814959-5dee1150-416d-11e8-8ec4-147df352766e.PNG)

note that may sites inducing [GitHub](https://help.github.com/articles/supported-browsers/) no longer support IE 
![image](https://user-images.githubusercontent.com/11149030/38814941-4f37c21e-416d-11e8-9524-d7fd71121517.png)

Present in release [v2.3.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.2)

**Comment by htmlboss** [comment]
That's weird since the template is using bootstrap. I'll take a look.
