### ISSUE TITLE
Very large transects fails

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#235]
Transects thumnail draws in the wrong direction for plots that are more the 180 deg wide (more than half the world) 

![image](https://user-images.githubusercontent.com/11149030/39009148-6cea32c2-43e5-11e8-9565-2d8f81286801.png)

![image](https://user-images.githubusercontent.com/11149030/39009157-71763804-43e5-11e8-8e67-aba41c321803.png)

The issue is still present in version:  [v2.3.2](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.2)

**Comment by Jeffreydaw** [comment]
note that this problem affects the data that actually gets plotted. If more than half the worldwide it will draw wrapping in the wrong direction.  ![image](https://user-images.githubusercontent.com/11149030/39063402-9153182a-44a5-11e8-8c20-1581c1a7c867.png)

**Comment by Jeffreydaw** [comment]
this is not a dateline problem, it is only if the plot is more than 180 deg wide, even if it is not crossing the dateline it is a problem.

**Comment by htmlboss** [comment]
Unreported edge case so I'll go ahead and close this. If any users report this as an issue, we can re-open it later.
