### ISSUE TITLE
variables not listed in datasetconfig.cfg still appear in the navigator 

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#245]
At least for some datasets, like Glorys V4, variables that are in the netcdf files but not listed in datasetconfig.cfg still appear in the navigator. 

Is there a way to restrict the variables list to only those that appear in datasetconfig.cfg? It would be helpful for datasets with many variables, some of which aren't needed in the navigator.

**Comment by nsoontie** [comment]
not sure if this matters but glorysv4 lists variables name explicitly in the aggregate.ncml file.

However, I don't think this is the reason for the mismatch in the datasetconfig variables because salishsea had the same issue without variables listed in aggregate.ncml

**Comment by geoffholden** [comment]
You can explicitly hide variables in datasetconfig.cfg, it's done for the fvcom_test dataset.

**Comment by nsoontie** [comment]
Thanks!
