### ISSUE TITLE
plotting/map.py no longer exists on dev but is being called here

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#247]
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/cd4c72330fc2e3cab0ca925a335b068470cc3b42/oceannavigator/views.py#L19

Noticed this after deleting all my .pyc files and then trying to run the navigator. Suddenly things break.

I have a fix but am weary of pushing straight to dev

**Comment by NoahGallant-MUN** [comment]
Reverted name back to map.py temporarily
dev branch no longer broken
