### ISSUE TITLE
Not Displaying stick plot correctly for point

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#255]
-Stick Plot not being generated correctly
-python3 and velocity fix merge testing
![image](https://user-images.githubusercontent.com/34169751/40671391-51376d1c-6346-11e8-838c-d29d4446530b.png)

**Comment by NoahGallant-MUN** [comment]
-Not unique to the GIOPS dataset

**Comment by nsoontie** [comment]
The velocity rotation mods only allows stick plots, quivers, etc for datasets with east/north components. I didn't rotated all of the GIOPS daily files so I think this is ok.

Exclude giops daily, riops monthly, glorys v3 in your checks
