### ISSUE TITLE
Stats Table broken for Area Plot

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#268]
Broken for all variables
gives the same value for all statistics

may be related to issue #236

**Comment by NoahGallant-MUN** [comment]
The stats table won't even load anymore

**Comment by htmlboss** [comment]
We've decided to re-write the stats file completely. I'll be doing up a design doc for the public api. For the first implementation, we'll most likely revert to similar behaviour before #236 was fixed. It'll be modular enough to add dateline support if users need it. Performance-wise the stats api is doing very easy calculations (min, max, mean, median, etc), so results should be presented near instantly.
