### ISSUE TITLE
copy button broken

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#3]
the main map view copy button is broken. 

**Details**:
Once the link button is pressed on the main map a popup window appairs. The copy button on this window does not actually copy the displayed link to the clipboard.  The link can be copied with Ctrl-c or by right clicking.  

**version** 
The problem is known to exist in Commit: https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/commit/2ae745d475744bcf4770982f1de55c05b3b29238

**Comment by htmlboss** [comment]
Bigly Changes (#1) contains a fix.
