### ISSUE TITLE
 SerializationWarning for plots and tiles

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#304]
getting a  SerializationWarning in the navigator log file when tiles or area plots are created. An example error is below but the message is appairing a lot in the log file. It seems to be there for every variable. it was noticed in commit a1ad77aafd26d4376846c7949975ca9e24036f2f and still present in version [v3.0.1](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v3.0.1).

    conventions.py:537: SerializationWarning: variable 'vosaline' has multiple fill values {1e+30, 1e+20}, decoding all values to NaN.
      stack_char_dim=stack_char_dim)

@htmlboss have you seen this before.

**Comment by Jeffreydaw** [comment]
the datasupply has changed again, this may resolve the problem for new files. 

June 1, 2018
    votemper:missing_value = -99.f ;

aug 1, 2018:
    votemper:_FillValue = 1.e+20f ;
    votemper:missing_value = 1.e+30f ;

oct 10, 2018 
    votemper:_FillValue = 1.e+30f ;
    votemper:missing_value = 1.e+30f ;



NOTE: missing valeus and fille value are filtered out automaticly by xarray. they can be viewed by using
`Dataset(' _filepath_ ',  'r')`

**Comment by htmlboss** [comment]
Gonna go ahead and close this up since we have not seeing this warning for a long time. The underlying data has changed drastically, and we're also using xArray globally now.
