### ISSUE TITLE
Default dataset and variable causes errors in Nav2Go

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#310]
If someone does not subset Giops Daily w/ Temperature, the site will throw `KeyNotFound` exceptions. This happens because so far we've assumed Giops w/ Temperature to be the default state of the site, and that this dataset will always be available. With Nav2Go we need to load the available datasets, query variables, then proceed with plotting tiles (which should have been done in the first place). This will be an interesting issue to solve since we're making all these calls concurrently and dont' want to freeze up the site, or make it look buggy...either way we need to define a load order for the site.

**Comment by NoahGallant-MUN** [comment]
Done in #408 
Will now default to the first dataset in the returned list
