### ISSUE TITLE
Hovmoller plot causes Internal Server Error

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#313]
Internal server error occured: Dimensions of C (886, 100) are incompatible with X (100) and/or Y (2); see help(pcolormesh)

![image](https://user-images.githubusercontent.com/11149030/44149273-061a9df0-a076-11e8-86a5-630226d7466d.png)

![image](https://user-images.githubusercontent.com/11149030/44149290-20fbf0c4-a076-11e8-9860-91a9379ef7c7.png)

**Comment by NoahGallant-MUN** [comment]
There was no errors on the server??
![image](https://user-images.githubusercontent.com/34169751/44208900-5589bd00-a13c-11e8-902f-543839a4a22d.png)

**Comment by NoahGallant-MUN** [comment]
Those were the only 2 hovmoller plots made yesterday

**Comment by htmlboss** [comment]
With #687 Hovmoller plots now only crash when invalid timestamps are passed through the API, as intended.
