### ISSUE TITLE
Separate states between the main map and the product page

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#318]
@EricaRogers44

**Comment by htmlboss** [comment]
#333 has the first iteration of this for the Area plots only. Point and Lines will come soon after we're sure things are working correctly.

**Comment by NoahGallant-MUN** [comment]
I didn't get the chance to add the Sync option back in, if it's needed it shouldn't be terribly difficult.

Therefore, States are completely separate
