### ISSUE TITLE
Restore "Mixed Layer Depth" to GIOPS variables

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#319]

**Comment by Jeffreydaw** [comment]
the datasetconfig.json file is just missing a whole bunch of values

**Comment by htmlboss** [comment]
GIOPS Forecast has this variable. Our currently shown GIOPS daily does not. We've received a "new GIOPS" dataset from datamart which has all the variables including Mixed Layer Depth.

**Comment by htmlboss** [comment]
The code is ready however dory thredds is having performance issues.

**Comment by htmlboss** [comment]
Mixed Layer Depth is available for any dataset that has it. Performance issues are resolved with the index tool implementation.
