### ISSUE TITLE
Add animations of variables over time

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#328]

**Comment by NoahGallant-MUN** [comment]
@FraserO  @EricaRogers44 @jamesprayner 
If anyone has any ideas to how this should look from a User Interface perspective that would be useful.
A similar feature can be seen here: https://www.windy.com (hit the play button at the bottom)
Did we want to display it at the bottom of the map in a similar way? or try a different approach?

**Comment by FraserO** [comment]
HI Guys
                 The approach windy has is very visual and very nice.
However it is important that people understand the that the lines moving along are not equivalent to drift lines, but they are simply an animated way to represent the stream function (integral of currents) and the direction of currents/winds at a given time.

So the question is:
                What does the user get out of windy.com


·         An idea of where the fronts are

·         An idea of current/wind intensity and direction …

I have no idea how they animate the stream function the way they do:
Weather it’s a random number generator for starting points, and how long the tail is on a a highlighted track


So I think this is an interesting idea, but we need to discuss why we need this and what priority we put it as a functionality ….

Kindest Regards

Fraser






Fraser JM Davidson
Research Scientist, Physical Oceanography
Oceanography Section

Fraser JM Davidson
Chercheur, Oceanographie Physique
Section Oceanographie

DFO-NAFC, 80 East White hills Rd.
P.O. Box 5667, St. John’s, NL. A1C 5X1
Tel: 709-772-2418 Fax: 709-772-5315 Fraser.Davidson@dfo-mpo.gc.ca<mailto:Fraser.Davidson@dfo-mpo.gc.ca>

**Comment by NoahGallant-MUN** [comment]
That was something we were looking at too, but I think this issue, and what I was referencing is the timeline at the bottom of the screen. So it moves between 10 days and changes the colourmap in the background.

Similar to how you would watch a radar animation.

https://i.gifer.com/Bc6f.gif

**Comment by NoahGallant-MUN** [comment]
In terms of the stream animations though, it could be useful for things like velocity, where when it's only a colour you can't really tell which direction it's going. The stream animations would be similar to the vector arrows you can superimpose when you do an area plot.

**Comment by FraserO** [comment]
Am in complete agreement if it’s looked at as the animation of velocities and people find that helpful ..

Basically this would be a plotting function that includes animation on the display.  Where would the animation be done, by the browser in Java Script?

Fraser


Fraser JM Davidson
Research Scientist, Physical Oceanography
Oceanography Section

Fraser JM Davidson
Chercheur, Oceanographie Physique
Section Oceanographie

DFO-NAFC, 80 East White hills Rd.
P.O. Box 5667, St. John’s, NL. A1C 5X1
Tel: 709-772-2418 Fax: 709-772-5315 Fraser.Davidson@dfo-mpo.gc.ca<mailto:Fraser.Davidson@dfo-mpo.gc.ca>

**Comment by NoahGallant-MUN** [comment]
Yes in the Javascript, there is a library which renders it on top of the openlayers using a canvas

**Comment by NoahGallant-MUN** [comment]
Implemented in pull request in #408
