### ISSUE TITLE
Velocity arrows on 45deg angle

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#332]
All velocity arrows are on a 45 degree angle pointing towards the bottom left corner in an area of the gulf of st lawrence.

http://navigator.oceansdata.ca/plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.14790067990293%2C-61.50987348837183%5D%2C%5B48.334426691438296%2C-64.67335126680658%5D%2C%5B45.974542886131985%2C-64.61000821871087%5D%2C%5B45.88181707744468%2C-60.837127187674504%5D%2C%5B48.14790067990293%2C-61.50987348837183%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%220%2C2.053171157836914%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A721%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D&format=png&size=10x7&dpi=144

**Comment by Jeffreydaw** [comment]
@NoahGallant-MUN how was this created? I am unable to replicate.

**Comment by Jeffreydaw** [comment]
I see this on 
[May 15th 2018](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B49.566294215628915%2C-53.427734375%5D%2C%5B45.2266522623662%2C-56.416015625%5D%2C%5B44.66680661924937%2C-47.89062499999998%5D%2C%5B49.16564118706361%2C-46.308593749999986%5D%2C%5B49.566294215628915%2C-53.427734375%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-50.1758%22%2C%2252.9471%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22time%22%3A797%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%220%2C3%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A917%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A917%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A917%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D) as well. it seems to have something to do with the underlying layer around the costs being read as large values. probably values that are suppose to be strings.

**Comment by Jeffreydaw** [comment]
when accessing the same data on trinity the problem is not seen
![image](https://user-images.githubusercontent.com/11149030/45382933-67983780-b5e4-11e8-9d6b-af616db040a1.png)

**Comment by Jeffreydaw** [comment]
GLOYRS_v4  maybe related. have not looked into this one 
![image](https://user-images.githubusercontent.com/11149030/45821441-c84e0100-bcc3-11e8-8583-f92794cbdcbd.png)

[link](http://navigator.oceansdata.ca/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-51.1343%22%2C%2249.6606%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22glorys4%22%2C%22dataset_attribution%22%3A%22GLORYS2V4%20from%20Mercator%20Ocean%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A%2212%22%2C%22time%22%3A275%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%5B0%2C3%5D%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A926%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A926%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22iicevelu%2Ciicevelv%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A926%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A3%7D)

**Comment by NoahGallant-MUN** [comment]
From what I can see this is no longer an issue
