### ISSUE TITLE
API Script Template Giving Low Resolution Image

### ISSUE THREAD

**Issue by jwfh** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#359]
Python and R scripts do not pass GET parameter "dpi" to API request whereas the Save Image and Get Link buttons on the web interface do and both specify 144dpi. Without this, the app defaults to 72dpi. 

```
dpi = 144

#Assemble full request - converts json object to url
url = base_url + urlencode({
    "query": json.dumps(query), 
    "dpi": dpi
})
```

**Comment by NoahGallant-MUN** [comment]
These changes should be made to the scriptGenerator.py file

**Comment by Ocean-Navigator** [comment]
Fixed

**Comment by NoahGallant-MUN** [comment]
Fixed
