### ISSUE TITLE
Pre-defined line, point and area are no longer available

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#363]
The drop down for the line, area, point no longer have the pre-defined options, i.e. NL transects, EBSAs, ...

**Comment by NoahGallant-MUN** [comment]
I'll look into this when I got home... I think this is an API problem

**Comment by htmlboss** [comment]
I'm surprised this issue has been left open for so long. I'll take a look.

**Comment by htmlboss** [comment]
![image](https://user-images.githubusercontent.com/5572045/57926815-e0901300-7886-11e9-8128-5f81b376091c.png)

**Comment by htmlboss** [comment]
@dwayne-hart is in the process of setting up a docker image for me so I can play around with the uwsgi settings. This could be what we're looking for: https://uwsgi-docs.readthedocs.io/en/latest/Options.html#chdir

**Comment by htmlboss** [comment]
Fixed in v3.2.0
