### ISSUE TITLE
RIOPS Temperature in Kelvin

### ISSUE THREAD

**Issue by jamesprayner** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#371]
From Fraser's Email:
Also noticed that for RIOPS all the fields are in Kelvin.   All the NETCDF files for the models are in Kelvin, but I guess there is a conversion in the code for RIOPS and potential other models (I didn’t check)  that is not being done in the code.   Haleh could you check the code for differences in RIOPS and GIOPS with respect to conversion from Kelvin to Celcius?

**Comment by jmunroe** [comment]
Is this related to #212 ?

**Comment by jamesprayner** [comment]
This is probably the settings in datasetconfig.json.

**Comment by NoahGallant-MUN** [comment]
Yeah, I would try changing the units in the config file. If that fixes it, maybe we should document somewhere what the units are supposed to be since this appears to be a reoccurring problem.

**Comment by jamesprayner** [comment]
This occurs when trying to access all RIOPS data sets (daily, monthly, forecast) except the dataset actually named RIOPS. The oceannavigator/datasetconfig.json file in production has the offending datasets listed as being in degrees Celsius, where the netCDF files are actually in Kelvin. This JSON file is also formatted somewhat incorrectly, so a fix to this issue should include reformatting the file to avoid future issues.

**Comment by jmunroe** [comment]
So can this issue be closed?

**Comment by NoahGallant-MUN** [comment]
If it's not fixed in #373 it should be in Geoffs middle layer.
