### ISSUE TITLE
Ditch jQuery date picker

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#382]
Mixing jQuery and React is a bad idea. Also, our datepicker isn't compatible with newer version of npm (big oopsie), which is required for Ubuntu 18.04...so we need to dump it. At the moment there is only one possible candidate to replace it and it's still missing the month/year date picking. There's someone working on it now so hopefully when I get back I can integrate it.

https://github.com/Hacker0x01/react-datepicker/

**Comment by NoahGallant-MUN** [comment]
I've replaced the datepicker in the main map time selection but I haven't updated the point, line, area, etc
The main map one I replaced it with is custom because I couldn't find the one I wanted that was also able to do time ranges (for time animation)

**Comment by NoahGallant-MUN** [comment]
So for the plots I switched over to the react-dates which I think is made by Airbnb, and I'm going to use a drop down box for the hour and minutes.

Any thoughts?
It does time ranges nicely which i like.

**Comment by NoahGallant-MUN** [comment]
Just noticed that you had referenced a date picker you wanted to use.
Are you okay with the one I implemented?

**Comment by NoahGallant-MUN** [comment]
This is done, will be rolled out with new UI changes.
