### ISSUE TITLE
Add version numbering

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#386]
It is often to helpful to be able to relate back a deployed version of the software to a particular snapshot of the code base.  This can be done both with git commits and version numbers.  

A version string could appear in an 'About' dialogue box or discreetly in the lower left corner of the UI.  The log files should also print this information out when the server is started.
 
Starting points:

- [Semantic Versioning](https://semver.org/)
- [GitVersion](https://gitversion.readthedocs.io/en/latest/

**Comment by NoahGallant-MUN** [comment]
I think this would be a good discussion for our technical meetings. It's a good idea and we can probably display the version number were we have the cookie disclaimer (bottom Left).

Jeffrey used to do the versioning, so we are currently on v3.0.4 which was last updated on sept 28, 2018.
I think either Geoff's changes, or my UX changes would probably be another major version, but that should also be discussed.

**Comment by dwayne-hart** [comment]
Yes, I’d second this being talked about during the meeting. We’d be lookin
at versi 4.1.0 or 5.0.0. After taking in Noah’s work after Geoff’s.

Best,
Dwayne

**Comment by NoahGallant-MUN** [comment]
Mine and Geoff's changes combined will be version 4.0.0
I'm going to lower the priority, because the version is now displayed to the user, but not done the way James M would like (it's just statically set).

**Comment by jmunroe** [comment]
I've just hit this issue again with me getting confused with what version of the application is currently live at http://navigator.oceansdata.ca compared to master.  

Did we also recently do a version bump to v6.0 ?

I also assume addition of the version number in the UI is buried within @NoahGallant-MUN UI changes.
