### ISSUE TITLE
Map goes Black on change to Arctic/Antarctic Projection

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#388]
In my new UI changes, when I switch from the global to either the antarctic or the arctic projection, the map goes black. I can still see the coordinates displayed in the bottom left, and I can move the map around and zoom in and out, I just can't see anything.

Has anyone seen this issue before?

This is the error I'm getting when I switch projections (single error) or move the map (many errors)
![image](https://user-images.githubusercontent.com/34169751/54778384-49467080-4bf3-11e9-9a42-d434fb1d6946.png)

**Comment by NoahGallant-MUN** [comment]
@htmlboss

**Comment by htmlboss** [comment]
Is the flask console showing that it's sending any tiles back?

Looks like OpenLayers (ol) is trying to do something with x/y coords and it's missing data.

**Comment by NoahGallant-MUN** [comment]
it's not even sending tile requests... the map component is still mounted

**Comment by htmlboss** [comment]
So it's somewhere between mounting and where it would be sending ajax requests for tiles: https://programmingwithmosh.com/javascript/react-lifecycle-methods/ may help with narrowing down where. Otherwise just spam print statements to see.

**Comment by NoahGallant-MUN** [comment]
yeah that's what I thought, just thought you might have seen it before

**Comment by NoahGallant-MUN** [comment]
Do you know if the EPSG:32661 and EPSG:3031 are support by proj4 by default? or could I be missing a package or something? Do you know where to find a list of the default supported projections?

**Comment by NoahGallant-MUN** [comment]
Have you ever used the open layers debug 'mode'. and do you know how to use it?

**Comment by NoahGallant-MUN** [comment]
So, this issue seems to have been caused by a layer that was no longer being used, and therefore the projection for that layer was not being updated. Because the layer didn't have the correct projection, the map failed to load.
