### ISSUE TITLE
Subset Failed

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#397]
http://localhost:5000/subset/?&output_format=NETCDF4&dataset_name=giops_day&variables=votemper&min_range=35.94033399654003,-71.97265625&max_range=45.195692974058915,-52.724609375&time=,&user_grid=0&should_zip=0

**Comment by jmunroe** [comment]
@FraserO @NoahGallant-MUN and will email @geoffholden on this issue.

**Comment by NoahGallant-MUN** [comment]
![image](https://user-images.githubusercontent.com/34169751/56134165-6fe29780-5f64-11e9-8813-76cd9c347837.png)

**Comment by geoffholden** [comment]
Looks like lines 131 & 132 of netcdf_data.py should be changed to look like 134.
variable_list only contains data variables, not the coordinate variables.

**Comment by NoahGallant-MUN** [comment]
Thanks! that worked
