### ISSUE TITLE
Write documentation for Github Pages.

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#40]
* There needs to be a discussion about how we want to organize the documentation for the navigator, and how will make contributions to various areas (usage, reporting bugs, keyboard commands, etc.).

**Comment by htmlboss** [comment]
I'm kinda swamped with the side-by-side stuff so I'll probably focus on contributing to the keyboard shortcuts area (since these things really only show themselves in the javascript documentation).

**Comment by Jeffreydaw** [comment]
I copied over the content I had in the wiki to the git pages and moved what was there to a "Technical Details" section at the bottom of the page.

**Comment by Jeffreydaw** [comment]
I've added some information about the side-by-side view but it should probably be expanded.
