### ISSUE TITLE
map colour avarages can cross land 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#45]
The way the colors are displayed can cause the data to be picked up across land boundaries when they are thin. 

This can lead to problems in areas such as the Panama canal where there is hot water on one side of the land and cold water on the other. But because the only thing that is done to pick the color is to look at all the data within a certain radius and to average based on the weight of how close they are. If the land is thinner than the specified radius the data can be accessed across it leading to misleading results (ex, hot looking water on the side of the land where the water is cold). 

to fix this the colour selection tools need to know when they are next to land instead of just being covered by a mask. 

Discovered when talking to Geoff about  bug https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/7

**Comment by Jeffreydaw** [comment]
This problem is still present in version [v2.1.3](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.1.3) and has been present since before we started using version markers (ie pre [v2.1.0](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.1.0)   

the image below shows an example of this problem. the pink arrow shows where the map is rendering its circle. And the green arrow shows the side of the peninsula where that data point it is using is located. 
![land jumping](https://user-images.githubusercontent.com/11149030/32326258-27b7052c-bfb5-11e7-829b-395b1b848adf.png)
![land jumping2](https://user-images.githubusercontent.com/11149030/32326611-70ac5060-bfb6-11e7-8597-b2fe0f570d3f.png)

**Comment by Jeffreydaw** [comment]
@htmlboss did you fix this? It does not look like it's a problem anymore in your new code. But you make no reference to fixing it in your pull request. 

![fixedlandcrossings](https://user-images.githubusercontent.com/11149030/36543145-78ef6dc0-17bd-11e8-8e9d-51c6b9af01a6.png)

**Comment by Jeffreydaw** [comment]
this change has been rolled out in version [v2.3.0](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/releases/tag/v2.3.0)

**Comment by htmlboss** [comment]
Appears to be fixed now. We can reopen if needed.

**Comment by Jeffreydaw** [comment]
Note this problem is probably not fixed just reduced
