### ISSUE TITLE
Implement API script generation for Class4

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#461]
We have received a request for generating an API script for Class4. Turns out we don't support that yet...

tl:dr Let's get rid of this message:
![image](https://user-images.githubusercontent.com/5572045/60886183-dad20080-a22b-11e9-90c3-4f52cf1df37d.png)

**Comment by jamesprayner** [comment]
I'll be adding this functionality to the current version of the code to make the feature available, but this script generation code needs to be rewritten afterwards.

**Comment by jamesprayner** [comment]
#463
