### ISSUE TITLE
environment.yml is broken

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#465]
The version of gdal we're requesting doesn't exist anymore. It's been superseded by `gdal=2.4.1=py36hf242f0b_2`. However, this breaks other package dependencies: 
```sh
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal==2.4.1=py36hf242f0b_2 -> libgdal==2.4.1=h1500935_2 -> geotiff[version='>=1.5.1,<1.5.2.0a0']
  - libgdal==2.4.1=hdb8f723_0 -> geotiff[version='>=1.4.2,<1.5.0a0']
Use "conda search <package> --info" to see the dependencies for each package.
```

In the meantime, @dwayne-hart is going to do up a tarball of the working environment on Dory and shove it into http://navigator.oceansdata.ca/cdn/

**Comment by jamesprayner** [comment]
Of course
