### ISSUE TITLE
Enable OpenLayers zoom slider

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#482]
I'm thinking the version with the slider in between the zoom buttons.
![image](https://user-images.githubusercontent.com/5572045/64077766-f5fe4100-ccad-11e9-97a4-f2e14634f54c.png)

Example code:
https://openlayers.org/en/latest/examples/zoomslider.html

**Comment by NoahGallant-MUN** [comment]
Done... Changes in UI Update

**Comment by NoahGallant-MUN** [comment]
Changes seem to have disappeared in my UI, will add to current nav
