### ISSUE TITLE
Expose interpolation method to Javascript UI

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#49]
* In an "advanced" option, allow the user to switch between available data interpolation options.
* Interpolation should be done in nemo.py.

**Comment by htmlboss** [comment]
Already have the code stashed on my computer. Just need to tweak the ui placement of the options.

**Comment by htmlboss** [comment]
Code is found in the interpolation branch

**Comment by Jeffreydaw** [comment]
here is an example of the improvement 
![interplulation notfixed](https://user-images.githubusercontent.com/11149030/36545014-7b455daa-17c2-11e8-8662-7f1283c8a74f.png)

http://navigator.oceansdata.ca/public/?/tiles/EPSG:3857/giops_day/votemper/716/0/-1,3/5/11/11.png

![interplulation fix](https://user-images.githubusercontent.com/11149030/36545021-7dde7d08-17c2-11e8-9ebf-3a6b44828c97.png)

http://navigator.oceansdata.ca//tiles/v0.1/gaussian/25/10/EPSG:3857/giops_day/votemper/716/0/-1,3/5/11/11.png

(links not live at time of comment)
