### ISSUE TITLE
RIOPS hourly timestamps with new indexing tool

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#494]
**Describe the bug**
The RIOPS hourly timestamps show repeated values for the same date/time. Eg. multiple selections for 19:30

**To Reproduce**
Launch navigator.
Select RIOPS Hourly (3D).
Select a day (eg. August 25, 2019)
Look at the times listed. There are multiple entries for a single time (eg. 19:30 has 7). When I select any of the 19:30's no data loads.
Similar for RIOPS Hourly (Surface)

**Expected behavior**
24 time stamps for each day in RIOPS Hourly datasets - 00:30 to 23:30

**Screenshots**
![image](https://user-images.githubusercontent.com/9750865/65423206-086a2700-dde3-11e9-8f33-ceead36223df.png)

**Desktop (please complete the following information):**
 - OS: windows 10?
 - Browser: chrome
 - Version 77.0.3865.75 (Official Build) (32-bit)

**Comment by htmlboss** [comment]
Just checked the API request and it's coming from the backend.

![Screenshot at 2019-09-23 10-38-24](https://user-images.githubusercontent.com/5572045/65427905-ed50e480-dded-11e9-8a6e-23b0c2b0ba8b.png)

**Comment by htmlboss** [comment]
Ran the following inside the RIOPS-Hourly-Surface.sqlite3 database: 
```sql
SELECT
                timestamp, COUNT(timestamp) c
            FROM
                TimestampVariableFilepath tvf
                JOIN Timestamps ts ON tvf.timestamp_id = ts.id
                JOIN Variables v ON tvf.variable_id = v.id
            WHERE
                variable = 'votemper'
            GROUP BY timestamp HAVING c > 1
			ORDER BY c ASC;
```

Reveals 139 duplicate rows with upto 9 duplicates per timestamp. One of two things is happening:
1. some of our riops files are duplicated (or internal timestamps are messed up, this is easy to check).
2. The indexing tool is getting bamboozled.

**Comment by htmlboss** [comment]
The tool is operating correctly. The issue the RIOPS hourly source changed the filename + format of the netcdf files to include forecasts (i.e. dual timestamps).

**Comment by htmlboss** [comment]
To be specific, the new RIOPS v2.0 comes with the forecasts built in. So we've got the dual timestamp issue which the indexing tool and the navigator both don't support. In the meantime, we've deleted the offending files and will re-index the "old" hourly files.
