### ISSUE TITLE
Sound Channel Calculations Optimization

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#512]
I think these functions can be vectorized fairly easily if we observe a couple of things:
* If we're only returning an array of shape (Y, X) (i.e. a 2D thing), and more specifically, only the top of the depth dimension, would it make sense to simply allocate a new ndarray of shape (Y, X) and return that? I'm a little hesitant to be over-writing the speed values and then returning the top layer, since it's a little unclear what's going on. By manipulating `speed` instead of a fresh `result` array (or something similar), there are `49*Y*X` wasted memory operations (since the 50-th, or "top", layer is being returned). The next bullet point about slicing will describe this.
* Observe the slicing operations: Use `speed[:,y,x] = sld_idx` as an example. I see two issues here: we are modifying the `speed` array with data that is not identical in scope to the speed of sound. I've already noted this so that's the end of that discussion. The second (and more relevant point for this bullet) is the slicing. Let's break down what `[:, y, z] = 0` means. For a given `x` and `y`, we're replacing all depth (`z`) values with 0. Ok that's fine when you consider this statement by itself. But what about if we only return the "top" `z` slice (`z = 0`)? Now we've replaced 49 depth values with data we'll never use anyway. Here's a small example:
```python
In [1]: import numpy as np                                                                                                                                                   

In [2]: a = np.random.rand(2, 2)                                                                                                                                             

In [3]: a                                                                                                                                                                    
Out[3]: 
array([[0.29482528, 0.81081683],
       [0.78039902, 0.61391043]])

In [4]: a.shape                                                                                                                                                              
Out[4]: (2, 2)

In [5]: a[:, 0] = np.nan                                                                                                                                                     

In [6]: a                                                                                                                                                                    
Out[6]: 
array([[       nan, 0.81081683],
       [       nan, 0.61391043]])
```

Now to analyse this algorithm: from a 30,000 foot view, what are we doing? For every (y, x) in (Y, X), we are performing an operation along a single z column. So right off the bat we have `Θ(XY*50)` complexity. Can the number of calculations be reduced? No. We need to do this calculation. Ok fine. The next question: is each iteration of the loop mutually exclusive? As in, does every iteration depend on data from other iterations? No. Ok, so now we've got a good candidate for vectorization. In python, it is generally preferred to vectorize instead of parallelize. Why? Parallelization is difficult to implement correctly in python, and nowadays, vectorized code can actually be faster due to SIMD (Single Instruction Multiple Data). Modern CPUs use the latest implementation via AVX registers. These can vary from 128-bit widths all the way up to 512-bit widths. Is that a lot? Oh yeah. With 512-bit wide registers, the CPU can calculate the dot product of 16 32-bit floats (or 8 64-bit doubles) in 1 instruction. That is insanely fast. Anyway enough rambling. Numpy supports vectorization very nicely due to it's complied c-code. Will it work here? Not sure: https://stackoverflow.com/questions/27624678/how-to-vectorize-3d-numpy-arrays
This will take some playing with (probably in a jupyter notebook or in an isolated environment outside of the navigator). But my point is, this *can* be sped up.

A cube visualisation to help:
![image](https://user-images.githubusercontent.com/5572045/67390684-b64e2a00-f577-11e9-8c2b-2d0847544ead.png)

cc @nsoontie

_Originally posted by @htmlboss in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/pull/510_

**Comment by htmlboss** [comment]
Addressed in #726 #669 #643 #753
