### ISSUE TITLE
UI changes - Default colormap range broken

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#513]
**Describe the bug**
When switching between variables on the new UI instance, clicking the Default button to reset the colormap range doesn't work. This is may be related - the default colormaps don't match with what we're used to seeing (for example, temperature and salinity)

**To Reproduce**
* Load GIOPS Daily
* Switch from temperature to salinity
* Press default and nothing happens 

**Expected behavior**
Salinity colormap defaults are applied (probably like 30 to 35 ish)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser firefox

**Comment by NoahGallant-MUN** [comment]
Fixed
