### ISSUE TITLE
RIOPS hourly datasets not loading previous dates and shifting dates

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#517]
**Describe the bug**
When I select the RIOPS hourly dataset, the current date loads. I change the date/time and nothing loads. I change the the date /time again and the date jumps to the previous date selected. Again, nothing loads.

**To Reproduce**
* Load RIOPS Hourly (3D)
* Select Date Oct 1 2019,  Time 19:30 - nothing loads
* Select Date Oct 16 2019 , Time 16:30 - date jumps back to Oct 1 and nothing loads

**Expected behavior**
1. Selecting a new time shouldn't modify the date.
2. Data loads when a date/time is selected.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Additional context**
I'm guessing this is related to the new indexing tool. I wanted to capture the date shifting behaviour in this issue. I think we were already aware of the data loading issue.

**Comment by jmunroe** [comment]
Discussed at Nov 20, 2019 tech meeting.

**Comment by nsoontie** [comment]
This is related to issue #494
