### ISSUE TITLE
Can select months for which there is no data

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#52]
The Giops monthly allows for the selection of months that there is no data for. 

If there is a month (or months) missing in the files it is still displayed as an option for selection so long as there is a file that is for a month for some point before and after it.  It will show data for that previous selected month if picked.

![selection_021](https://user-images.githubusercontent.com/11149030/28930355-461a2e0e-784d-11e7-963e-d8b93619f238.png)
the picture is from trinity for which there is no data for 2016

**Comment by NoahGallant-MUN** [comment]
Time Is handled differently now so this should be fixed
