### ISSUE TITLE
MERCATOR PSY4 and GLORYS 12 data

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#523]
What data had you downloaded from the LAS from MERCATOR on GLORYS 12 and where is it located on Hank.
 
It looks like the GLORYS 12 data is available on CMEMS FTP site.  I am not sure if that is full resolution data on original grid, or decimated by a factor of 2.

1)      Dwayne tried downloading monthly GLORYS12 data 3D from CMEMS data and it was fast.  (ie done)
2)      Dwayne is looking at FTP daily GLORYS 12 by FTP to take 20 days
3)      There would still be 2D hourly files to get outstanding which are not on the FTP CMEMS site
a.       Could we still proceed with LAS, or should I ask for a MERCATOR FTP service
b.        The priority there initially would be U and V ,  then  T, SSH, S, and eventually other variables  Mixing Depth, Turbo-cline Depth….(if they are in there).  
c.       James:  Would it still be painfully slow on OPENDAP to get U V hourlies, and T, SSH S… individually

**Comment by jmunroe** [comment]
From an email "RE : acceleration de mettre les donnees GLORYS 12 sur le Navigator"

> MERCATOR service desk has there total transfer of data by day and 900 Go (ie. almost 1 Tb) on there Open DAP logs.
> If we look at a total of 80 TB we want to download that would take 90+ days assuming we took the whole bandwidth of 0.9 TB per day. 
> I think those measurements from Mercator correspond to our download speed that James saw.
 > What I would suggest if possible with marc Tresol, is to set up a small test of trying to Rsync to the Navigator server and comparing it to the open dap download.
> Then based on that outcome, there may opportunity to figure out how to increase the transfer speed

**Comment by dwayne-hart** [comment]
James, for the GLORYS 12 data. Which directory is hosting that information?

**Comment by dwayne-hart** [comment]
The following directories are present...

- GLOBAL_REANALYSIS_PHY_001_025/ |   | 11/4/19, 8:26:00 AM

- GLOBAL_REANALYSIS_PHY_001_030/ |   | 10/28/19, 1:30:00 PM

- GLOBAL_REANALYSIS_PHY_001_031/ |   | 10/28/19, 9:04:00 PM

I have most of the GLOBAL_REANALYSIS_PHY_001_030. The historical daily should finish by November 12.

**Comment by jmunroe** [comment]
For the little amount of data I had pulled earlier, it was in /data/mercator 

Happy for it to be somewhere else.
