### ISSUE TITLE
Fix names for RIOPS forecast on dory-dev

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#528]
RIOPS 10-day Forecasts - Can we rename as RIOPS 2-day Forecasts?

Also is RIOPS 10-day Forecast 2D Grid the lat lon grid?

What is the difference between these datasets and the Canadian Coast Guard datasets?

**Comment by htmlboss** [comment]
Fixed
