### ISSUE TITLE
private github/gitlab repository 

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#530]
We need a private gitlab or github repository for storing our data pipeline scripts and scripts that contain sensitive information.

**Comment by jmunroe** [comment]
Sensitive information like passwords and access keys should not really be stored in scripts as plain text. There are various ways of doing this with environment variables, or encryption, but this may take a little time to figure this out.

Here's a blog post on some of the risk and some options to mitigate those concerns:  https://www.freecodecamp.org/news/how-to-securely-store-api-keys-4ff3ea19ebda/

In the short term, you are welcome to use this private GitHub repository:

jmunroe/ocean-navigator-private

I will add @nsoontie and @dwayne-hart to that repo and anyone else who should be added upon request.  While I think passwords should be kept off of GitHub, this private repo would be a reasonable place to store still sensitive information like network settings, machine names, file paths, etc. 

@dwayne-hart do you have any advice here on the security side?

**Comment by htmlboss** [comment]
Production systems in the private sector use the environment variable approach. Not saying that's what we should do, but it's good point to be knowledgeable about what everyone else is doing.
