### ISSUE TITLE
Where did GIOPS 10-day forecast go?

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#545]
The GIOPS 10-day forecast is no longer available on navigator.oceansdata.ca. We have users asking for it. We need to add it back.

The GIOPS 10-day forecasts is available on http://dory-dev.cs.dal.ca/ but it is not up-to-date (October 17-26, 2019 is the last available). We need to check the data pipelines and/or the aggregation in thredds.

**Comment by dwayne-hart** [comment]
I have updated the dory-dev THREDDS instance to use the new feed from SeDOO [...]/data/eccc_forecasts_netcdf/giops_forecast/2D/LL. Note that we also have 3D information and both grid and polar stereographic information if users wish to avail of it.

I ran into an issue trying to display the same content in the production instance. I have to open a separate ticket for the indexing tool and we should discuss with the group how we look to present the 00 and 12 data sets.
