### ISSUE TITLE
New UI: Improve French Translation

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#570]
New UI has incomplete translations:
![Screenshot at 2019-12-17 09-04-27](https://user-images.githubusercontent.com/5572045/70995734-d0097a80-20ab-11ea-855c-a58e1f239ff0.png)

**Comment by jmunroe** [comment]
@NoahGallant-MUN Please add the required tags so that the translation will work correctly.  Support available from @FraserO upon request for translations.
