### ISSUE TITLE
New UI: Permalink not working

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#583]
Seems like the generated permalink isn't updating based on the global state.

Example: I selected water velocity for giops daily, and changed the map location but the generated link doesn't reflect those values:
![Screenshot at 2019-12-17 09-31-50](https://user-images.githubusercontent.com/5572045/70997422-a2becb80-20af-11ea-907e-25989d27434e.png)

**Comment by jmunroe** [comment]
We need to comment out the permalink button to remove this functionality for now.
