### ISSUE TITLE
Default colourmaps for variables are not being displayed

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#585]
The old colourmaps that changed with the selected variable are now uniform across several variables. Much research has gone into "optimal" colours for displaying particular data which shouldn't be glossed over without discussion. Another discussion is do we even want the colourmaps changed?

Temperature:
![Screenshot at 2019-12-17 09-38-43](https://user-images.githubusercontent.com/5572045/70997914-9ab35b80-20b0-11ea-959e-6c25f1444603.png)

Water Velocity:
![Screenshot at 2019-12-17 09-40-48](https://user-images.githubusercontent.com/5572045/70998035-e0702400-20b0-11ea-9a0e-52775c82c841.png)

Salinity:

**Comment by NoahGallant-MUN** [comment]
Can you add a list of the variables you want changed, and the corresponding colourmap to change each one to?

**Comment by nsoontie** [comment]
Does this help? 
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blame/266ccd684a28f266bc9deaf86d2adfbd7ca23bc6/plotting/colormap.py

**Comment by NoahGallant-MUN** [comment]
Yes, but that's also somewhat confusing because it doesn't look like any of the colourmaps were actually changed

**Comment by nsoontie** [comment]
Ok, so is there a bug somewhere that is changing the colormap?

**Comment by NoahGallant-MUN** [comment]
Haven't had a chance to look yet, will comment when I know more
