### ISSUE TITLE
New UI: Removing default data layer doesn't remove the panel

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#587]
When clicking the remove layer button on the default data layer panel, the map layer appears to be deleted, but the panel itself remains. Is this the intended behaviour?

Example:
![Screenshot at 2019-12-17 09-52-21](https://user-images.githubusercontent.com/5572045/70998717-807a7d00-20b2-11ea-8a9a-31f340f8940c.png)

**Comment by NoahGallant-MUN** [comment]
Yes that's the intended behaviour, to remove the panel you click the 'x' at the top.

If you want to discuss changing this we can discuss though.

**Comment by NoahGallant-MUN** [comment]
Can I close this then?

**Comment by jmunroe** [comment]
yes
