### ISSUE TITLE
New UI: Arctic & Antarctic projection not displaying data

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#589]
![Screenshot at 2019-12-17 10-06-28](https://user-images.githubusercontent.com/5572045/70999711-7f4a4f80-20b4-11ea-9fc1-34b4c376cc74.png)
![Screenshot at 2019-12-17 10-10-42](https://user-images.githubusercontent.com/5572045/70999990-11eaee80-20b5-11ea-8021-6add24f6437a.png)

**Comment by NoahGallant-MUN** [comment]
How can I replicate this? The data loads for me.

![image](https://user-images.githubusercontent.com/34169751/71000235-52486d80-20b1-11ea-9851-5817d45c21a0.png)

**Comment by htmlboss** [comment]
Thanks for the check. Could be a network issue on our end >.>
