### ISSUE TITLE
New UI: Behaviour of adding new data layers

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#590]
![Screenshot at 2019-12-17 10-21-40](https://user-images.githubusercontent.com/5572045/71000898-a99d0c80-20b6-11ea-9ae6-3333b99e6b84.png)

**Comment by NoahGallant-MUN** [comment]
Did you hit the add layer button?

**Comment by NoahGallant-MUN** [comment]
![image](https://user-images.githubusercontent.com/34169751/71001158-0d253b00-20b3-11ea-92c3-16768a44acf2.png)

**Comment by htmlboss** [comment]
That did the trick lel. Would it possible to make new layers display on the map by default? New users may not notice the add layer button without prior hints.

**Comment by NoahGallant-MUN** [comment]
I didn't do that so it's more bandwidth friendly. It's likely that if your creating a new layer your probably not showing giops daily temperature a second time.

Thoughts?

**Comment by htmlboss** [comment]
I'd imagine the duplicate giops tiles are cached by the web browser locally so that shouldn't be an issue.

**Comment by NoahGallant-MUN** [comment]
You should rename the issue to something more accurate now, and I looked into this and it wasn't a 2 second fix like I thought it would be so I'm going to put this aside because I feel like we have more important things

**Comment by jmunroe** [comment]
Adding a new layer should open a modal dialog box.

Not an immediate concern.
