### ISSUE TITLE
points, lines, and shapes not saved

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#6]
the points, lines, and shapes are not saved by the link button. 

**Details**
The link button that is used for both the main map and the more detailed views in the popup window does not have the shape or drawing that the user has made on the main map.  This would probably be good to have. 

Verson: https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/commit/2ae745d475744bcf4770982f1de55c05b3b29238

**Comment by htmlboss** [comment]
Compare branch contains a working solution to this.
