### ISSUE TITLE
Ubuntu 16.04 EOL -> Move to 18.04 ASAP

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#601]
Our conda environment is built for 16.04 which went EOL in April 2019 (oops). We need to re-build our conda environment for 18.04.

cc @jamesprayner your favourite thing to do :rofl: 

blocked by #608

**Comment by htmlboss** [comment]
@dwayne-hart update:
"I’ve got the production version of the conda toolchain of the navigator working. I’m having trouble getting the system to run the command “yarn run dev”. I am able to build the oceannavigator/frontend content. But when I launch the either the gunicorn or python scripts I do not see anything in the browser. Also, there are no issues reported in the terminal window where the commands are run. Something to look into further this week coming."

**Comment by dwayne-hart** [comment]
Further update. The building of the dev frontend code appears to have moved a little further. I've uploaded a copy of my terminal CLI. Is it worth our time to run a separate ON build with eslint?
 
[CLI-history-20200105.txt](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/files/4024103/CLI-history-20200105.txt)

**Comment by dwayne-hart** [comment]
Looking at the yarn process it appears to be stuck... 

> root@u1804-on:~# strace -p 12703
strace: Process 12703 attached
epoll_pwait(3, [], 1024, 892, NULL, 8)  = 0
openat(AT_FDCWD, "/proc/self/stat", O_RDONLY) = 10
read(10, "12703 (node) R 5476 12703 335 34"..., 1023) = 304
close(10)                               = 0
epoll_pwait(3, [], 1024, 1000, NULL, 8) = 0
openat(AT_FDCWD, "/proc/self/stat", O_RDONLY) = 10
read(10, "12703 (node) R 5476 12703 335 34"..., 1023) = 304
close(10)                               = 0
epoll_pwait(3, [], 1024, 1000, NULL, 8) = 0
openat(AT_FDCWD, "/proc/self/stat", O_RDONLY) = 10
read(10, "12703 (node) R 5476 12703 335 34"..., 1023) = 304
close(10)                               = 0
epoll_pwait(3, [], 1024, 1000, NULL, 8) = 0
openat(AT_FDCWD, "/proc/self/stat", O_RDONLY) = 10
read(10, "12703 (node) R 5476 12703 335 34"..., 1023) = 304
close(10)                               = 0

**Comment by dwayne-hart** [comment]
At present we are able to use Ubuntu 18.04 LTS LXD/lXC containers with the new implementation of the Navigator toolchain. Along with the way we implement both nvm and yarn in an unprivileged account.

However, we do need to update the Navigator toolchain as it relying on package versions that are outdated and some of their functionality has been deprecated.
