### ISSUE TITLE
Re-create conda environment file

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#608]

**Comment by dwayne-hart** [comment]
Do we really want to build the existing current version of conda being used on Ubuntu 16.04 on Ubuntu 18.04? The reason for asking is that there are a couple of packages that have been deprecated and may cause issues with trying to get it running on 18.

**Comment by dwayne-hart** [comment]
I may have a fix for the conda environment not being able to be replicated. I stumbled into it while working on CentOS 6 and 7. I'll start the process of trying it on Ubuntu 18.04.

**Comment by htmlboss** [comment]
I think it would be a good exercise even if we come across deprecated packages because at the moment, we don't know what will work and what won't work. Once we know what will be broken, we can start thinking about workarounds.

**Comment by htmlboss** [comment]
Dwayne has a spec file ready for testing in a fresh container.

**Comment by htmlboss** [comment]
Spec file is working as intended.
