### ISSUE TITLE
Load dataset info modal per-dataset instead of concatenating all datasets

### ISSUE THREAD

**Issue by douglatornell** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#636]
**Priority (low, medium, high)**
Priority: medium

**Is your feature request related to a problem? Please describe.**
re: the dataset info modal that appears when the `?` above the dataset selector is clicked
It was not obvious to me that the contents of that modal are a scrollable concatenation of the `help` content from all of the enabled datasets in `datasetconfig.json`.

**Describe the solution you'd like**
I think it would be more intuitive if the `help` content for only the dataset being displayed were shown in the modal. Obviously this would require some kind of coupling between the modal's content, the dataset selector, and perhaps change events from the selector.

**Additional context**
N/A

**Comment by JustinElms** [comment]
dataset info modal was removed in favor of the info/help modal.
