### ISSUE TITLE
Hourly time stamps reflect the users's time zone but should be in UTC 

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#649]
**Describe the bug**
Datasets with an hour picker are not displaying the correct time. The hours should be in UTC but I've noticed that user's in different time zones have a different list of hours. For Newfoundland there is usually 4.5 hour offset and for BC there is a 7 or 8 hour offset. 

**To Reproduce**
Select CCG RIOPS dataset. The time's do not align with UTC. Rather there is a 4.5 hour offset when the user is in Newfoundland and an 8 hour offset with the user is in BC.

**Expected behavior**
All times should be UTC. Ocean models are reporting in UTC.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**

**Comment by htmlboss** [comment]
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/39148025a8ea260d964f0ddac611167f889d76c2/oceannavigator/frontend/src/components/TimePicker.jsx#L125

There are a few instances where we add the local timezone offset in `TimePicker`. Shouldn't be a big issue to fix.

**Comment by htmlboss** [comment]
Turns out the jquery time picker widget itself is converting the dates to the client time zone, and there doesn't appear to be an option to no do that. Only way around this is to change widgets...

**Comment by htmlboss** [comment]
What we could do is change the time picker label to display the user's timezone instead of UTC. Thoughts?

The code to do that:
```js
Intl.DateTimeFormat().resolvedOptions().timeZone
```

**Comment by nsoontie** [comment]
If we did that, would the hours align with the correct date? The order of the times listed puzzles me a bit. 

For example, if I walk through the times by clicking the arrows, I start on Day 1 14:30 which progresses to Day 1 19:30 and then jumps to Day 2 20:30  which progresses to Day 2 23:30 and then Day 2 00:30.... The order seems wrong.

**Comment by nsoontie** [comment]
Is it possible to keep track of the client's timezone offset with UTC? If so, we could just add that offs\set back to the hour time stamps when generating the list that is displayed on the front end.
