### ISSUE TITLE
API Stability: Dead Endpoints

### ISSUE THREAD

**Issue by jamesprayner** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#680]
`/api/v1.0/data/`
`/api/v1.0/timestamp_for_date/`

Are not present anywhere in the front end code of the navigator. The only reason to keep them around would be if someone was hitting the endpoints directly.
When fed a time larger than the 32bit integer limit, `data` fails to convert to timestamp. As it is not present in our code I see no reason to fix or re implement.

**Comment by htmlboss** [comment]
I think `/api/v1.0/timestamp_for_date/` is supposed to be "interpolating" a time from a given dataset and finding the closest time in the other given dataset. Thing is, this operation can be done in `O(log(n))` time. The implementation that's in the dead code is `O(n)`

We don't need this functionality currently but it would be good to have.

**Comment by htmlboss** [comment]
`/api/v1.0/timestamp_for_date/` deleted in b39ddde

**Comment by htmlboss** [comment]
As for `/api/v1.0/data/`, it handled the pop-up balloon functionality on the main map on the website. We turned that off to avoid conflicts with the OpenLayers event handler when drawing points/lines/areas on the map.

That endpoint should stay.
