### ISSUE TITLE
Landing page errors. Missing static/ resources

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#684]
**Describe the bug**
navigator.oceansdata.ca appears to be missing static/ resources such as jquery.min.js

**To Reproduce**
Browse to http://navigator.oceansdata.ca using either Firefox or Chrome.

**Expected behavior**
Landing page should open without issues.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dwayne-hart** [comment]
This is due in part to using a reverse proxy.

**Comment by dwayne-hart** [comment]
The issue has been resolved and should no longer be an issue.
