### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#7]
At areas where there is a high gradient on the map there is sometimes some blotchiness that can be seen. 

**Details**
This needs to be investigated further but at times it can be seen that the colors in the map seem to be many overlaying circles where the centers of the circles are a darker color and there is a color gradient that comes out from the center. The fix to the problem may be as simple as to turn the resolution up but it should be determined and documented how the pixel rendering is done.

[little dots from far out](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%2280.5049%22%2C%228.1663%22%5D%2C%22zoom%22%3A5%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%2228.540948486328148%2C30.447564697265648%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

[close zome problem ](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%22-31.5077%22%2C%2249.0896%22%5D%2C%22zoom%22%3A6%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%2214.041741943359398%2C16.246759033203148%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

[circle problem 1](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%22-80.5057%22%2C%2252.9895%22%5D%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%22-1.0411437988281023%2C9.986627197265648%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

[circle problem 2](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%22-267.0856%22%2C%2279.8605%22%5D%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%22-1.6618103027343523%2C-1.3244384765624773%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

and where the offset problem in the southern hemisphere (issue https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/4 ) is present there cycles are more clear.
[circle problem 3](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%22146.9863%22%2C%22-16.5000%22%5D%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A484%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%2222.353021240234398%2C26.165612792968773%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

note: you must press auto and or play with the range settings to see the effect since the range settings are not saved by the link.

**Comment by Jeffreydaw** [comment]
it was suggested today in the meeting that we try changing the blur from a Gaussian blur to some other blur. a different blur of blur value may reduce the look.

**Comment by Jeffreydaw** [comment]
here are 2 other examples that help to highlight the problem
[PEI](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%22-62.3355%22%2C%2246.0091%22%5D%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A504%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%2221.834%2C21.949243164062523%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D) to see the effect set the varible Range to Min = 21.834, Max = 21.949 setting the Min to 21.934 also produces an interesting result. 
[vertical line of circles](http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22121.2402%22%2C%22-3.4770%22%5D%2C%22zoom%22%3A8%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A504%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%2228.504%2C29.45%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%7D)

**Comment by Jeffreydaw** [comment]
after talking with people at the conference last week I think that bicubic interpolation may not be that much of a drain on our system

**Comment by nsoontie** [comment]
The circles show up when the number of interpolated grid cells is much bigger than the number of original grid cells. Otherwise, the interpolation looks gridded (see Grid size section of this [notebook](https://github.com/nsoontie/ocn_nav/blob/master/notebooks/interpolation/Playing%20with%20interpolation%20and%20plotting-RIOPS.ipynb) ). Matplotlib's imshow can smooth the gridded look using the interpolation key word.

My thoughts were to have an interpolated grid that depends on the size of the original grid and then use imshow to produce the image. But I don't see how this can work with the tiles and would make things difficult for comparing between models of different resolution. 

Other suggestions: switch to a different interpolation package
https://www.earthsystemcog.org/projects/esmpy/
http://xesmf.readthedocs.io/en/latest/ 

Or use @htmlboss 's Gaussian interpolation for the tiles and/or user selected interpolation.

**Comment by htmlboss** [comment]
So I've supposedly finalized the feature to select/tweak the interpolation stuff in the front-end. I also have an experimental layout for the left sidebar. I've tested most things and nothing appears to be broken. Wouldn't mind some more testing: http://fbi-surveillance-van:5000/public/

**Comment by htmlboss** [comment]
#49
