### ISSUE TITLE
GIOPS Historical Daily Data

### ISSUE THREAD

**Issue by forbea8** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#717]
I have been attempting to retrieve GIOPS Historical Daily data for several location in the Canadian Arctic. I am looking for the variables " Salinity, Temperature, V-Wind, U-Wind, and all available depth levels 

The issue is when ever I select a subset, I receive an Internal Error page. 

Below is a sample of the Python 3 API generated from the Ocean Navigator site. I generating the API through Ocean Navigator website using Google Chrome, Windows 10, and running the API in Jupyter Notebook. 

This also does not work when trying to extract a NETCDF file directly from the Ocean Navigator site. 

----------------------------------------------------------------------------------------------------
```
import requests
import os
import shutil
from urllib.request import urlopen
from urllib.parse import urlencode
from contextlib import closing
import json


def requestFile():
   # json object for the query
   query = {"dataset_name":"historical_giops_day",
"max_range":"60.39988178482815,-64.76265762350522",
"min_range":"60.35752655655634,-64.95079851360062",
"output_format":"NETCDF4",
"should_zip":0,
"time":"2139004800,2139004800",
"user_grid":0,
"variables":"v_wind,vosaline,votemper,u_wind"}


   # Assemble full request
   base_url = "http://navigator.oceansdata.ca/api/v1.0/subset/?"
   url = base_url + urlencode({"query": json.dumps(query)})
   print(url)


   #Open URL and save response
   data_file = requests.get(url, stream=True)
   dump = data_file.raw
   # change this if you want a different save location
   location = os.getcwd()
   with open("script_output.nc", "wb") as location:
      print('Saving File')
      shutil.copyfileobj(dump, location)
      print('Done')


if __name__ == '__main__':
   requestFile()
```
-------------------------------------------------------------------------------------------------------

**Comment by jamesprayner** [comment]
Hi @forbea8,
Thanks for taking an interest in the Navigator and logging an issue. A fix has been suggested in #720 and will be active next rollout (planned Tuesday, April 21st).
-James R
