### ISSUE TITLE
Class4 cache files not being generated/saved automatically

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#732]
Class4 files support a caching mechanism `/home/buildadm/cache/oceannavigator/class4_files.pickle`  

This file does not seem to be automatically generated if it does not exist.  

Error message:  

> Warning: Unable to open cache list of Class 4 files: [Errno 2] No such file or directory: '/home/buildadm/cache/oceannavigator/class4_files.pickle'

Relatedly, is the script `generate_class4_list.py` the correct script to generate this class4_files.pickle.

Finally, is a "pickle" file the best way of caching this file. It appears to actually be a JSON file ... so why don't we cache it as that?

**Comment by dwayne-hart** [comment]
This has been resolved in [PR #733](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/pull/733). Once that is approved you'll be able to configure a cron job to run the code to generate the CLASS4 pickle file.

**Comment by dwayne-hart** [comment]
The PR has completed and closing this ticket due to resolution of the issue.
