### ISSUE TITLE
Velocity arrows show incorrect direction

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#735]
**Describe the bug**
In Area plots, when plotting Water Velocity arrows, the direction of the arrows is incorrect. 

**To Reproduce**
Area plot -> Water Velocity -> Add Water velocity arrows
This bug occurs for several datasets including CMEMS, GIOPS LatLon. However, it appears inconsistently. The velocity arrows display correctly for some users but not for others. Here is the [link](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B56.990223074171666%2C-56.42212033271789%5D%2C%5B39.49273539428748%2C-70.87524116039276%5D%2C%5B41.04253048249387%2C-37.515872716903694%5D%2C%5B54.89064980356312%2C-37.3596179485321%5D%2C%5B56.990223074171666%2C-56.42212033271789%5D%5D%5D%7D%5D%2C%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22dataset%22%3A%22cmems_daily%22%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22cmems_daily%22%2C%22dataset_attribution%22%3A%22E.U.%20Copernicus%20Marine%20Service%20Information%20(CMEMS)%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22time%22%3A604692%2C%22variable%22%3A%22magwatervel%22%2C%22variable_scale%22%3A%5B0%2C3%5D%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A604692%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A604692%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22magwatervel%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%220%2C3%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A604692%2C%22variable%22%3A%22magwatervel%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D) that generated the screenshot below.

**Expected behavior**
Velocity arrows display correctly. The results are consistent for all users.

**Screenshots**
![image](https://user-images.githubusercontent.com/9750865/84778358-74b63780-afbd-11ea-8662-68eaab5ad1c6.png)

**Desktop (please complete the following information):**
Chrome, IE

**Additional context**

We've seen this issue in the past and it was corrected by updating the datasetconfig entry from
 ```"vozocrtx,vomecrty": { "name": "Water Velocity", "envtype": "ocean", "unit": "m/s", "scale": [0, 3], "scale_factor": 1 }```
to
``` "magwatervel": { "name": "Water Velocity", "envtype": "ocean", "unit": "m/s", "scale": [0, 3], "equation": "magnitude(vozocrtx, vomecrty)", "dims": ["time_counter", "depth", "y", "x"] }```

however, that does not appear to be the issue here. 

This issue is also difficult to reproduce because some users are experiencing the issue but others are not. Efforts to clear the browser cache do not help.

**Comment by nsoontie** [comment]
For reference, the arrows should look something like what is in this notebook: https://nbviewer.jupyter.org/github/nsoontie/ocn_nav/blob/master/notebooks/velocity/Check%20CMEMS%20climatology%20quivers.ipynb

**Comment by nsoontie** [comment]
I traced this issue to
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/47f81decaec81837f0c5d733aebe4639fc78d997/plotting/map.py#L273-L274

 `component_vars` must have the x-velocity in the first element and the y-velocity in the second element. This assumption is not guaranteed in the way `get_data_vars_from_equation` is written. 

There are a few coding issues that break (or could break) this assumption:
1. The magnitude equation in datasetconfig.json must have the x-component first, and the y-component second (eg. `magnitude(uo, vo)`. The code then attempts to identify the order of the variables listed in the equation to determine which is the x-component and which is the y-component. If the datasetconfig.json entry does not conform to this convention then the result is incorrect. From a mathematical perspective, the order in the magnitude function does not matter so this convention could easily be forgotten.
2. In `utils.get_data_vars_from_equation` Line 63 identifies the 'words' in an equation (e.g. variables, etc). Casting as a `set` does not preserve the order of these words. Hence, the assumption that `component_vars` contains x, then y is broken. This explains the inconsistent behaviour we have been seeing.
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/10fd23f3be8aa6e484a11f9d74235688831bd986/data/utils.py#L45-L66 

To solve this problem, I suggest that we explicitly state the eastward and northward vector components in the datasetconfig file. We could do this by adding two new keys to the `magwatervel`, `magicevel` entries of the datasetconfig.json:
`"magwatervel": { "name": "Water Velocity", "unit": "m/s", "scale": [0, 1], "equation": "magnitude(uo, vo)",  "dims": ["time", "depth", "latitude", "longitude"] ,
 "east_vector_component": "uo",  "north_vector_component": "vo"}`

Then we could identify the correct vector components to use in `map.py` through these datasetconfig entries.

The downside is that the datasetconfig files are large and difficult to maintain. But the upside is that we are explicit and clear about which components are used in the quiver plots.

**Comment by nsoontie** [comment]
On another note, the way we identify vector variables could be improved if we adopt the above strategy.

At the moment, we identify a variable as a vector variable if its name contains "mag"
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/37c1e32c0f4e1638ad470dd3b6afecaabca01ab3/oceannavigator/dataset_config.py#L166-L180

We could now identify vector variables as ones that have east_vector_component and north_vector_component entries in their datasetconig.

This change would prevent misclassification of variables which have 'mag' in their names but aren't vectors.

**Comment by dwayne-hart** [comment]
I agree with your "explicitly state the eastward and northward vector components in the datasetconfig file" suggestion. Having defined these additional key value pairs would remove the guess work in the code and ensure of the desired result.
