### ISSUE TITLE
Trying to incorporate model_rdsps datasets

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#750]
**Describe the bug**

> [2020-08-18 00:04:38 -0230] [3244] [ERROR] Error handling request /api/v1.0/tiles/gaussian/25/10/EPSG:3857/rdsps/etas/2229681600/0/-0.5,0.5/1/1/0.png
> Traceback (most recent call last):
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 271, in handle
>     keepalive = self.handle_request(req, conn)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/ubuntu/Ocean-Data-Map-Project/routes/api_v1_0.py", line 785, in tile_v1_0
>     'scale': scale,
>   File "/home/ubuntu/Ocean-Data-Map-Project/plotting/tile.py", line 186, in plot
>     args.get('neighbours')
>   File "/home/ubuntu/Ocean-Data-Map-Project/data/model.py", line 122, in get_area
>     latitude, longitude, depth, variable, time, return_depth=return_depth
>   File "/home/ubuntu/Ocean-Data-Map-Project/data/nemo.py", line 230, in get_point
>     latvar, lonvar = self.__latlon_vars(variable)
>   File "/home/ubuntu/Ocean-Data-Map-Project/data/nemo.py", line 173, in __latlon_vars
>     raise LookupError("Cannot find latitude & longitude variables")
> LookupError: Cannot find latitude & longitude variables
> 

**To Reproduce**
datasetconfig.json file has the following entry...

>     "rdsps": {
>         "envtype": ["ocean", "ice"],
>         "url": "/data/db/rdsps.sqlite3",
>         "name": "31. Storm surge model outputs (instantaneous values) - LatLon",
>         "quantum": "hour",
>         "type": "forecast",
>         "time_dim_units": "seconds since 1950-01-01 00:00:00",
>         "enabled": false,
>         "cache": 6,
>         "climatology": "http://navigator.oceansdata.ca:8080/thredds/dodsC/climatology/Levitus98_PHC21/aggregated.ncml",
>         "attribution": "The Canadian Centre for Meteorological and Environmental Prediction",
>         "lat_var_key": "lat",
>         "lon_var_key": "lon",
>         "help": " ",
> 
>         "variables": {
>             "etas": { "name": "Sea Storm Surge", "envtype": "ocean", "unit": "m", "scale": [-0.5, 0.5], "dims": ["time_counter", "lat", "lon"] }
>         }
>     }

some of the SQLite3 index database content regarding file locations...

> 241|/data/dd.weather.gc.ca/model_rdsps/atlantic-nw/netcdf/12/20200817T12Z_MSC_RDSPS-Atlantic-North-West_ETAS_SFC_LatLon0.033x0.033_P055.nc
> 242|/data/dd.weather.gc.ca/model_rdsps/atlantic-nw/netcdf/12/20200817T12Z_MSC_RDSPS-Atlantic-North-West_ETAS_SFC_LatLon0.033x0.033_P137.nc

header information retrieved from one of the dataset files from the model_rdsps repo...

> (navigator) ubuntu@177515a033a1:~$ ncdump -h /data/dd.weather.gc.ca/model_rdsps/atlantic-nw/netcdf/12/20200817T12Z_MSC_RDSPS-Atlantic-North-West_ETAS_SFC_LatLon0.033x0.033_P137.nc
> netcdf \20200817T12Z_MSC_RDSPS-Atlantic-North-West_ETAS_SFC_LatLon0.033x0.033_P137 {
> dimensions:
>         time_counter = 1 ;
>         lat = 541 ;
>         lon = 841 ;
> variables:
>         char crs_latlon ;
>                 crs_latlon:grid_mapping_name = "latitude_longitude" ;
>                 crs_latlon:earth_radius = 6371229. ;
>         float etas(time_counter, lat, lon) ;
>                 etas:units = "m" ;
>                 etas:missing_value = 1.e+30f ;
>                 etas:valid_min = -1000.f ;
>                 etas:valid_max = 1000.f ;
>                 etas:long_name = "storm_surge" ;
>                 etas:coordinates = "time_counter lon lat" ;
>                 etas:nomvar = "ETAS" ;
>                 etas:stdscale = 1.f ;
>                 etas:stdoffset = 0.f ;
>         float lat(lat) ;
>                 lat:long_name = "latitude" ;
>                 lat:standard_name = "latitude" ;
>                 lat:units = "degrees_north" ;
>         float lon(lon) ;
>                 lon:long_name = "longitude" ;
>                 lon:standard_name = "longitude" ;
>                 lon:units = "degrees_east" ;
>         double time_counter(time_counter) ;
>                 time_counter:units = "seconds since 1950-01-01 00:00:00" ;
>                 time_counter:long_name = "Time axis" ;
>                 time_counter:standard_name = "time" ;
>                 time_counter:title = "Time" ;
>                 time_counter:axis = "T" ;
>                 time_counter:calendar = "gregorian" ;
>                 time_counter:time_origin = "1950-01-01 00:00:00" ;
> 
> // global attributes:
>                 :Conventions = "CF-1.6" ;
>                 :title = "Storm surge model outputs (instantaneous values)" ;
>                 :institution = "Canadian Centre for Meteorological and Environmental Prediction" ;
>                 :contact = "ec.dps-client.ec@canada.ca" ;
>                 :source = "RDSPS 1.7.0, forecast" ;
>                 :creation_date = "2020-Aug-17 16:56:02 UTC" ;
> }
> 

**Expected behavior**
I'm not sure what had changed from their sample data that had worked on the GPSC and now that it has been pushed to production the same datasetconfig.json fails to render the information propery.

**Comment by JustinElms** [comment]
RDSPS has been retried. Will reopen if similar issue is encountered when we bring in GDSPS.
