### ISSUE TITLE
Issue with generating class4 pickle file

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#757]
At this time we have a directory called [...]/data/class4 which contains symbolic links to NetCDF files located in subdirectories 2019/20190825/class4_20200825_PSY3V3R3_orca025_profile.nc for example. In the older codeset in order to get a pickle create we had to create symbolic links within the [...]/data/class4 directory pointing to the source in the aforementioned storage location. While these symbolic links exist a new behaviour is found. The pickle is generated and when a user selects a date Ocean Navigator returns a string saying that the file is not found.

```FileNotFoundError: [Errno 2] No such file or directory: b'/data/class4/2020/class4_20200902_GIOPS_CONCEPTS_3.0_profile.nc'```

```
(navigator) [vagrant@onav bin]$ find /data/class4 -name class4_20200902_GIOPS_CONCEPTS_3.0_profile.nc -ls
    11030      4 lrwxrwxrwx   1  1009     1009           59 Sep  9 10:00 /data/class4/class4_20200902_GIOPS_CONCEPTS_3.0_profile.nc -> 2020/20200902/class4_20200902_GIOPS_CONCEPTS_3.0_profile.nc
    11031 334964 -rw-r--r--   1  1009     1009     343000296 Sep  8 20:03 /data/class4/2020/20200902/class4_20200902_GIOPS_CONCEPTS_3.0_profile.nc
```

**Comment by htmlboss** [comment]
It's because the paths are expected to be of the form `/some/path/YEAR/class_4_file.nc`. Not something that I can quickly change.

**Comment by dwayne-hart** [comment]
The ideal solution would be to remove the symbolic links once we have the
deployed Navigator instances updated with the newer code.

**Comment by douglatornell** [comment]
Related to the "no class 4 datasets after 2019" part of issue #785 , I think.
