### ISSUE TITLE
GIOPS Historical Data Diaily 

### ISSUE THREAD

**Issue by forbea8** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#759]
I am unable to download GIOPS Historical Daily Data. 

Below is the script that I am/have been using.  The script is exporting a .nc file, however, each file does not contain data.   I was able to download data in the past, but I am not seeing the dateset name in the options of datasets available now. Has this dateset been taken offline? Can I still access the data?   

----------------------------------------------------------------------------------------------------------------------------
import requests
import os
import shutil
from urllib.request import urlopen
from contextlib import closing
 
for x in range(2165788800,2166220800,86400):
   def requestFile():
    query = {"dataset_name":"historical_giops_day",
   "max_range":"69.8,-123.0",
   "min_range":"69.25,-124.25",
   "output_format":"NETCDF4",
   "should_zip":0,                     
   "time":"{},{}".format(x,x),  
   "user_grid":0,
   "variables":"votemper"}
 
      # Assemble full request
      base_url = "http://navigator.oceansdata.ca/api/v1.0/subset/?"
      url = base_url
      for key in query:
         url += f"&{key}={query[key]}"
      print(url)
 
      #Open URL and save response
      data_file = requests.get(url, stream=True)
      dump = data_file.raw
      location = os.getcwd()
      with open('votemper_' +'{}'.format(x)+'.nc', "wb") as location:
         print('Saving File')
         shutil.copyfileobj(dump, location)
         print('Done')
 
   if __name__ == '__main__':
      requestFile()

**Comment by nsoontie** [comment]
Yes, we did remove the GIOPS Historical Daily dataset because recent changes in the GIOPS file formats were making it difficult to maintain.

What time periods and variables are you looking for? Could the CMEMS Global Daily Reanalysis (1993-2018) suit your needs?

**Comment by forbea8** [comment]
That's too bad, but understandable. I have attempted to use the CMEMS Global Daily Reanalysis for the area, using that data changes my study parameters and becomes too difficult to augment this far into my research. 

I am looking for data from GIOPS Historical Daily dataset between August 18-22, 2018. The variables are vosaline (salinity) and votemper (temperature) for all depth levels. The bounding spatial limits are     "max_range":"70.000, -124.1",
   "min_range":"69.3, -124.4"

**Comment by nsoontie** [comment]
You can find the data you're looking for here:
ftp://navigator.oceansdata.ca/dwg/giops_subset/

It is a subset of the region you're looking at with a little bit of a buffer. 

I hope this helps!

**Comment by forbea8** [comment]
Thank you. This does help.
