### ISSUE TITLE
Issue with exporting to NetCDF-3 NC

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#769]
**Describe the bug**
When selecting an area of interest the plot renders and when we wish to export any variable(s) to a NetCDF-3 NC format. We receive an Internal Error.

**To Reproduce**
Request any area and variable(s) combination to export to NetCDF-3 NC. The error will be experienced immediately.

**Expected behavior**
Generation of a NetCDF-3 NC formatted file for post analysis.

**Screenshots**
![image](https://user-images.githubusercontent.com/44408505/96874374-a0a46680-1450-11eb-8e3b-400d853ac70e.png)

![image](https://user-images.githubusercontent.com/44408505/96874465-b580fa00-1450-11eb-89ec-ffe172e48964.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10 Enterprise 
 - Browser Chrome
 - Version Version 85.0.4183.121 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by dwayne-hart** [comment]
Update, the following information was taken from a test container which has the same issue as production when we try to export variables from the GIOPS 10 day Forecast 3D - LatLon

```
[2020-10-22 11:16:35 -0230] [4661] [ERROR] Error handling request /api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=giops_day&variables=votemper,vozocrtx,vomecrty,magwatervel&min_range=41.82992111131577,-56.591606140136726&max_range=48.345069092460676,-47.261466979980476&time=2235297600,2235297600&user_grid=0&should_zip=0
Traceback (most recent call last):
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 407, in subset_query_v1_0
    working_dir, subset_filename = dataset.nc_data.subset(args)
  File "/home/buildadm/Ocean-Data-Map-Project/data/netcdf_data.py", line 401, in subset
    lons=lon_vals, lats=lat_vals)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 495, in __init__
    super(SwathDefinition, self).__init__(lons, lats, nprocs)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 379, in __init__
    super(CoordinateDefinition, self).__init__(lons, lats, nprocs)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 86, in __init__
    raise ValueError('lons and lats must have same shape')
ValueError: lons and lats must have same shape
```

**Comment by nsoontie** [comment]
Thanks for logging this Dwayne. I'm wondering, what is the error when you export from RIOPS Forecast 3D - Polar Stereographic?

**Comment by dwayne-hart** [comment]
Good question Nancy. I do believe that we would get the same error as the plotting workflow is the same for all datasets. I did perform a test and unfortunately received the same identical internal server error.

```
[2020-10-22 16:18:02 -0230] [4657] [ERROR] Error handling request /api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=riops_fc_3dps&variables=votemper,density,vozocrte,vomecrtn,magwatervel&min_range=45.31787464828503,-52.71720886230469&max_range=52.22632734143076,-44.59178924560547&time=2234514600,2234514600&user_grid=0&should_zip=0
Traceback (most recent call last):
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 407, in subset_query_v1_0
    working_dir, subset_filename = dataset.nc_data.subset(args)
  File "/home/buildadm/Ocean-Data-Map-Project/data/netcdf_data.py", line 322, in subset
    subset = self.dataset.isel(**{lat_coord: y_slice, lon_coord: x_slice})
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 1523, in isel
    indexers_list = self._validate_indexers(indexers)
  File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 1409, in _validate_indexers
    raise ValueError("dimensions %r do not exist" % invalid)
ValueError: dimensions ['latitude', 'longitude'] do not exist

```

The URL that can be used on different sites;

```
REMOTE_SITE="http://192.168.2.221:5000"

${REMOTE_SITE}/api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=riops_fc_3dps&variables=votemper,density,vozocrte,vomecrtn,magwatervel&min_range=45.31787464828503,-52.71720886230469&max_range=52.22632734143076,-44.59178924560547&time=2234514600,2234514600&user_grid=0&should_zip=0
```
Then we can use the above URL to test once the code is corrected.

**Comment by nsoontie** [comment]
Thanks Dwayne. We receive the same internal server error but for different reasons as evidenced by changes in the Traceback. Interesting. I'll think on ideas for fixing the issues.

**Comment by dwayne-hart** [comment]
Nancy, you will want to focus on the [...]/data/netcdf_data.py Python file. It handles the exporting the data to a requested format.

**Comment by dwayne-hart** [comment]
Its interesting to see the following content in the file....

```
        # Workaround for https://github.com/pydata/xarray/issues/2822#issuecomment-475487497
        if '_NCProperties' in subset.attrs.keys():
            del subset.attrs['_NCProperties']

        # "Special" output
        if output_format == "NETCDF3_NC":

            GRID_RESOLUTION = 50

            # Regrids an input data array according to it's input grid definition
            # to the output definition

```

**Comment by nsoontie** [comment]
> Update, the following information was taken from a test container which has the same issue as production when we try to export variables from the GIOPS 10 day Forecast 3D - LatLon
> 
> ```
> [2020-10-22 11:16:35 -0230] [4661] [ERROR] Error handling request /api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=giops_day&variables=votemper,vozocrtx,vomecrty,magwatervel&min_range=41.82992111131577,-56.591606140136726&max_range=48.345069092460676,-47.261466979980476&time=2235297600,2235297600&user_grid=0&should_zip=0
> Traceback (most recent call last):
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
>     keepalive = self.handle_request(req, conn)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 407, in subset_query_v1_0
>     working_dir, subset_filename = dataset.nc_data.subset(args)
>   File "/home/buildadm/Ocean-Data-Map-Project/data/netcdf_data.py", line 401, in subset
>     lons=lon_vals, lats=lat_vals)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 495, in __init__
>     super(SwathDefinition, self).__init__(lons, lats, nprocs)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 379, in __init__
>     super(CoordinateDefinition, self).__init__(lons, lats, nprocs)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/pyresample/geometry.py", line 86, in __init__
>     raise ValueError('lons and lats must have same shape')
> ValueError: lons and lats must have same shape
> ```

This error occurs because the lat/lon datasets have 1D latitude and longitude variables. As such, their shapes may not match. To correct the problem, we could use np.meshgrid(lon_vals, lat_vals) and then pass the new gridded coordinates into the SwathDefinition() call.

**Comment by nsoontie** [comment]
> Good question Nancy. I do believe that we would get the same error as the plotting workflow is the same for all datasets. I did perform a test and unfortunately received the same identical internal server error.
> 
> ```
> [2020-10-22 16:18:02 -0230] [4657] [ERROR] Error handling request /api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=riops_fc_3dps&variables=votemper,density,vozocrte,vomecrtn,magwatervel&min_range=45.31787464828503,-52.71720886230469&max_range=52.22632734143076,-44.59178924560547&time=2234514600,2234514600&user_grid=0&should_zip=0
> Traceback (most recent call last):
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 279, in handle
>     keepalive = self.handle_request(req, conn)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 328, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 407, in subset_query_v1_0
>     working_dir, subset_filename = dataset.nc_data.subset(args)
>   File "/home/buildadm/Ocean-Data-Map-Project/data/netcdf_data.py", line 322, in subset
>     subset = self.dataset.isel(**{lat_coord: y_slice, lon_coord: x_slice})
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 1523, in isel
>     indexers_list = self._validate_indexers(indexers)
>   File "/home/buildadm/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 1409, in _validate_indexers
>     raise ValueError("dimensions %r do not exist" % invalid)
> ValueError: dimensions ['latitude', 'longitude'] do not exist
> ```
> 
> The URL that can be used on different sites;
> 
> ```
> REMOTE_SITE="http://192.168.2.221:5000"
> 
> ${REMOTE_SITE}/api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=riops_fc_3dps&variables=votemper,density,vozocrte,vomecrtn,magwatervel&min_range=45.31787464828503,-52.71720886230469&max_range=52.22632734143076,-44.59178924560547&time=2234514600,2234514600&user_grid=0&should_zip=0
> ```
> 
> Then we can use the above URL to test once the code is corrected.

This error occurs because we are trying to slice using the longitude and the latitude variable names. Rather, we should be slicing using the x/y dimension names. 

We could add x_dim_key, y_dim_key to the datasetconfig.json to access those names. But that seems clunky. Another option would be to access the dimensions list of self.dataset and then select the x/y dimensions from there (typically x is the last dimension, y is the second to last). These options need further investigation.

https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/cde8b1fb68dc4bdab98d0ce0f56a80a63cbbeb48/data/netcdf_data.py#L318-L322

Another note: some datasets, like lat/lon datatsets (or mercator?) have matching latitude/longitude variables names and dimension names. But others, like the polar stereographic datasets do not have matching latitude/longitude variables names and dimension names.

**Comment by douglatornell** [comment]
@nsoontie Does the `netcdf_data.NetCDFData.latlon_variables` property help resolve the issue? Just a guess, but would something like:
```python
 lat_coord, lon_coord = self.dataset.latlon_variables
  
 # Do subset along coordinates 
 subset = self.dataset.isel(**{lat_coord: y_slice, lon_coord: x_slice}) 
```
work?

**Comment by nsoontie** [comment]
Thanks @douglatornell. It looks like that property returns the variables names (i.e. nav_lon/nav_lat or latitude/longitude), but we want the two horizontal dimensions which are usually x/y, xc/yc or latitude/longitude. 

Maybe `netcdf_data.NetCDFData.dimensions` will do the trick? I would suggest the following: 

```python
dims = self.dataset.dimensions
x_coord = dims[-1]
y_coord = dims[-2]

 # Do subset along coordinates 
 subset = self.dataset.isel(**{y_coord: y_slice, x_coord: x_slice}) 
```

My only concern is the order of dimensions returned by `netcdf_data.NetCDFData.dimensions`. Is it always the same order as the dimensions of the variables it contains, which is typically (time, depth, y, x)? y_slice/x_slice were determined assuming the y-dimension is `variable_array.shape[-2]` and the x-dimension is `variable_array.shape[-1]`.

**Comment by douglatornell** [comment]
You're right - we can't rely on the order in `self.dataset.dimensions`. I stepped through the code for the 

`/api/v1.0/subset/?&output_format=NETCDF3_NC&dataset_name=riops_fc_3dps&variables=votemper,density,vozocrte,vomecrtn,magwatervel&min_range=45.31787464828503,-52.71720886230469&max_range=52.22632734143076,-44.59178924560547&time=2234514600,2234514600&user_grid=0&should_zip=0` 

call and found that `self.dataset.dimensions == ['depth', 'yc', 'xc', 'time']` for that case.

I can't see a good way of getting at the correct dimension/coordinate variables names to use in that `.isel()` call, and I find that ... annoying ...

**Comment by nsoontie** [comment]
Maybe we make a new property in the NetCDFData class? Something like this:

```python
@property
def yx_dimensions(self) -> List(str):
    dims = set(self.dimensions)

    ydim_candidates = set(['y', 'yc', 'latitude'])
    ydim = ydim_candidates.intersection(dims)
    try:
       ydim = ydim.pop()
    except KeyError:
        raise KeyError(f"None of {ydim_candidates} were found in dataset's dimensions {dims}".)

    xdim_candidates = set(['x', 'xc', 'longitude'])
    xdim = xdim_candidates.intersection(dims)
    try:
       xdim = xdim.pop()
    except KeyError:
        raise KeyError(f"None of {xdim_candidates} were found in dataset's dimensions {dims}.")

    return [ydim, xdim]
```

**Comment by douglatornell** [comment]
Yes, a new property like that is probably the way to go. I like your use of set intersection - makes for easy extension when we discover additional dimension names in other datasets.

Do you want to do the implementation PRs to resolve this issue, or would you like me to do that and you can review? I see 2 PRs related to this issue.

1. Resolution of the `ValueError: lons and lats must have same shape` by use of `numpy.meshgrid()` that you pointed out way up above.
2. Resolution of the `ValueError: dimensions ['latitude', 'longitude'] do not exist` by adding the `yx_dimensions` property.

**Comment by douglatornell** [comment]
By the way, what is the UI path/operation that leads to the `subset` API call? Or is this an example of use of the API separate from the frontend?

**Comment by nsoontie** [comment]
Thanks Doug! I'm not set up at the moment to modify the code so maybe it's best that you tackle the changes and I'll review?

I agree with the 2 PRs you've proposed.

**Comment by nsoontie** [comment]
To access the subset through the UI, do an area selection. Then there is a menu on left called Subset. You can select a variable (or several), then NetCDF-3 NC in Output Format, then Save and you should end up with an Internal Server Error. 

<img width="931" alt="subset" src="https://user-images.githubusercontent.com/9750865/97364212-a8b43a00-1886-11eb-99b4-e4e76caf30db.PNG">

**Comment by dwayne-hart** [comment]
The issue with exporting data to NetCDF-3 NC is fixed and datasets are created without issue.
