### ISSUE TITLE
LXD/LXC containers run out of memory resources

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#771]
[memory-resource-depletion.txt](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/files/5426413/memory-resource-depletion.txt)

I'm not sure what is causing the OOM daemon to terminate gunicorn processes. Is the end user requesting something that is causing a race condition to occur?

**Comment by dwayne-hart** [comment]
Event though the UptimeRobot site informed us that the site was down. We did not understand why... @nsoontie visited the navigator.oceansdata.ca site and was provided a 502 error and this comes about when the NGINX is not able to forward incoming requests to their defined end points.

> NGINX will return a 502 Bad Gateway error if it can't successfully proxy a request

At present we are using gunicorn version 20.0.4. The following logging information was copied from screen sessions running on u2004-onav-0, u2004-onav-1, and u2004-onav-2. The kernel ring buffer information presented after the line seperation on the host platform is provided. 

> **U2004-ONAV-0**
> 
> RuntimeError: can't start new thread
> [2020-12-01 11:31:51 +0000] [24306] [INFO] Unhandled exception in main loop
> Traceback (most recent call last):
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 211, in run
>     self.manage_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
>     self.spawn_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
>     self.spawn_worker()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 567, in spawn_worker
>     pid = os.fork()
> BlockingIOError: [Errno 11] Resource temporarily unavailable
> [2020-12-01 11:31:51 +0000] [24325] [INFO] Worker exiting (pid: 24325)
> [2020-12-01 11:31:51 +0000] [5313] [INFO] Worker exiting (pid: 5313)
> [2020-12-01 11:31:51 +0000] [24329] [INFO] Worker exiting (pid: 24329)
> [2020-12-01 11:31:51 +0000] [24341] [INFO] Worker exiting (pid: 24341)
> [2020-12-01 11:31:51 +0000] [24321] [INFO] Worker exiting (pid: 24321)
> [2020-12-01 11:31:51 +0000] [24335] [INFO] Worker exiting (pid: 24335)
> [2020-12-01 11:31:51 +0000] [24338] [INFO] Worker exiting (pid: 24338)
> [2020-12-01 11:31:51 +0000] [24333] [INFO] Worker exiting (pid: 24333)
> [2020-12-01 11:31:51 +0000] [24326] [INFO] Worker exiting (pid: 24326)
> [2020-12-01 11:31:51 +0000] [6079] [INFO] Worker exiting (pid: 6079)
> [2020-12-01 11:31:51 +0000] [24337] [INFO] Worker exiting (pid: 24337)
> [2020-12-01 11:31:51 +0000] [24331] [INFO] Worker exiting (pid: 24331)
> 
> **U2004-ONAV-1**
> 
> [2020-12-03 11:48:47 +0000] [27702] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
>     worker.init_process()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
>     super().init_process()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/base.py", line 140, in init_process
>     self.run()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 203, in run
>     callback(key.fileobj)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 124, in accept
>     self.enqueue_req(conn)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 114, in enqueue_req
>     fs = self.tpool.submit(self.handle, conn)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
>     self._adjust_thread_count()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
>     t.start()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 54, in sentry_start
>     return old_start(self, *a, **kw)  # type: ignore
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/threading.py", line 846, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> [2020-12-03 11:48:47 +0000] [27702] [INFO] Worker exiting (pid: 27702)
> [2020-12-03 11:48:48 +0000] [22727] [INFO] Unhandled exception in main loop
> Traceback (most recent call last):
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 211, in run
>     self.manage_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
>     self.spawn_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
>     self.spawn_worker()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 567, in spawn_worker
>     pid = os.fork()
> BlockingIOError: [Errno 11] Resource temporarily unavailable
> [2020-12-03 11:48:48 +0000] [22738] [INFO] Worker exiting (pid: 22738)
> [2020-12-03 11:48:48 +0000] [22745] [INFO] Worker exiting (pid: 22745)
> [2020-12-03 11:48:48 +0000] [22740] [INFO] Worker exiting (pid: 22740)
> [2020-12-03 11:48:48 +0000] [22754] [INFO] Worker exiting (pid: 22754)
> [2020-12-03 11:48:48 +0000] [22752] [INFO] Worker exiting (pid: 22752)
> [2020-12-03 11:48:48 +0000] [22750] [INFO] Worker exiting (pid: 22750)
> [2020-12-03 11:48:48 +0000] [25588] [INFO] Worker exiting (pid: 25588)
> [2020-12-03 11:48:48 +0000] [25264] [INFO] Worker exiting (pid: 25264)
> [2020-12-03 11:48:48 +0000] [16058] [INFO] Worker exiting (pid: 16058)
> [2020-12-03 11:48:48 +0000] [9307] [INFO] Worker exiting (pid: 9307)
> [2020-12-03 11:48:48 +0000] [22756] [INFO] Worker exiting (pid: 22756)
> /home/ubuntu/Ocean-Data-Map-Project/plotting/basemap.py:71: MatplotlibDeprecationWarning:
> The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
>   width=width
> /home/ubuntu/Ocean-Data-Map-Project/plotting/map.py:670: UserWarning: Log scale: values of z <= 0 have been masked
>   levels=[100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000])
> /home/ubuntu/Ocean-Data-Map-Project/plotting/map.py:670: UserWarning: Log scale: values of z <= 0 have been masked
>   levels=[100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000])
> /home/ubuntu/Ocean-Data-Map-Project/plotting/map.py:670: UserWarning: Log scale: values of z <= 0 have been masked
>   levels=[100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000])
> /home/ubuntu/Ocean-Data-Map-Project/plotting/map.py:670: UserWarning: Log scale: values of z <= 0 have been masked
>   levels=[100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000])
> 
> **U2004-ONAV-2**
> 
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/ubuntu/Ocean-Data-Map-Project/routes/api_v1_0.py", line 793, in tile_v1_0
>     'scale': scale,
>   File "/home/ubuntu/Ocean-Data-Map-Project/plotting/tile.py", line 186, in plot
>     args.get('neighbours')
>   File "/home/ubuntu/Ocean-Data-Map-Project/data/model.py", line 122, in get_area
>     latitude, longitude, depth, variable, time, return_depth=return_depth
>   File "/home/ubuntu/Ocean-Data-Map-Project/data/mercator.py", line 268, in get_point
>     data.values,
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataarray.py", line 407, in values
>     return self.variable.values
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/variable.py", line 387, in values
>     return _as_array_or_item(self._data)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/variable.py", line 208, in _as_array_or_item
>     data = np.asarray(data)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
>     return array(a, dtype, copy=False, order=order)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/array/core.py", line 1047, in __array__
>     x = self.compute()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/base.py", line 156, in compute
>     (result,) = compute(self, traverse=False, **kwargs)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/base.py", line 398, in compute
>     results = schedule(dsk, keys, **kwargs)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/dask/threaded.py", line 71, in get
>     pool = ThreadPool(num_workers)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/multiprocessing/pool.py", line 789, in __init__
>     Pool.__init__(self, processes, initializer, initargs)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
>     self._repopulate_pool()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
>     w.start()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/multiprocessing/dummy/__init__.py", line 48, in start
>     threading.Thread.start(self)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 54, in sentry_start
>     return old_start(self, *a, **kw)  # type: ignore
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/threading.py", line 846, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> [2020-12-03 12:23:01 +0000] [16210] [INFO] Worker exiting (pid: 16210)
> 
>==================================================================================
> 
> **ONAV**
> 
> on@dory:~$ dmesg -T | grep "Memory cgroup out of memory: Kill process"
> [Tue Dec  1 20:58:09 2020] Memory cgroup out of memory: Kill process 16382 (gunicorn) score 107 or sacrifice child
> [Tue Dec  1 20:58:09 2020] Memory cgroup out of memory: Kill process 4404 (gunicorn) score 107 or sacrifice child
> [Wed Dec  2 05:51:21 2020] Memory cgroup out of memory: Kill process 12744 (gunicorn) score 107 or sacrifice child
> [Wed Dec  2 05:51:58 2020] Memory cgroup out of memory: Kill process 16026 (gunicorn) score 109 or sacrifice child
> [Wed Dec  2 14:44:53 2020] Memory cgroup out of memory: Kill process 16024 (gunicorn) score 101 or sacrifice child
> [Thu Dec  3 04:40:27 2020] Memory cgroup out of memory: Kill process 16020 (gunicorn) score 97 or sacrifice child
> [Thu Dec  3 04:54:10 2020] Memory cgroup out of memory: Kill process 10115 (gunicorn) score 92 or sacrifice child
> [Thu Dec  3 04:54:11 2020] Memory cgroup out of memory: Kill process 14843 (gunicorn) score 92 or sacrifice child
> 
> on@dory:~$ free -h
>               total        used        free      shared  buff/cache   available
> Mem:           251G         73G        103G         35M         74G        177G
> Swap:           43G        8.3G         34G
> 
> on@dory:~$ uptime
>  09:37:58 up 15 days, 18:09,  4 users,  load average: 1.94, 1.86, 2.33

All containers were reporting less than 60 running processes each. 

> Name: u2004-onav-0
> Remote: unix://
> Architecture: x86_64
> Created: 2020/11/16 15:01 UTC
> Status: Running
> Type: persistent
> Profiles: default
> Pid: 22308
> Ips:
>   eth0: inet    10.0.3.112      vethPYYMLA
>   eth0: inet6   fe80::216:3eff:fe25:dbfb        vethPYYMLA
>   lo:   inet    127.0.0.1
>   lo:   inet6   ::1
> Resources:
>   Processes: 53
>   Memory usage:
>     Memory (current): 487.89MB
>     Memory (peak): 58.46GB
>   Network usage:
>     eth0:
>       Bytes received: 73.05MB
>       Bytes sent: 245.70MB
>       Packets received: 145008
>       Packets sent: 134599
>     lo:
>       Bytes received: 298.07kB
>       Bytes sent: 298.07kB
>       Packets received: 3536
>       Packets sent: 3536

> Name: u2004-onav-1
> Remote: unix://
> Architecture: x86_64
> Created: 2020/11/16 15:34 UTC
> Status: Running
> Type: persistent
> Profiles: default
> Pid: 24494
> Ips:
>   eth0: inet    10.0.3.3        veth9VRWM6
>   eth0: inet6   fe80::216:3eff:fe9c:fc6f        veth9VRWM6
>   lo:   inet    127.0.0.1
>   lo:   inet6   ::1
> Resources:
>   Processes: 54
>   Memory usage:
>     Memory (current): 282.55MB
>     Memory (peak): 64.00GB
>   Network usage:
>     eth0:
>       Bytes received: 111.26MB
>       Bytes sent: 287.37MB
>       Packets received: 259794
>       Packets sent: 255619
>     lo:
>       Bytes received: 1.95MB
>       Bytes sent: 1.95MB
>       Packets received: 23956
>       Packets sent: 23956

> Name: u2004-onav-2
> Remote: unix://
> Architecture: x86_64
> Created: 2020/11/16 15:38 UTC
> Status: Running
> Type: persistent
> Profiles: default
> Pid: 26781
> Ips:
>   lo:   inet    127.0.0.1
>   lo:   inet6   ::1
>   eth0: inet    10.0.3.60       vethB61G7L
>   eth0: inet6   fe80::216:3eff:fe51:15d2        vethB61G7L
> Resources:
>   Processes: 53
>   Memory usage:
>     Memory (current): 516.75MB
>     Memory (peak): 64.00GB
>   Network usage:
>     eth0:
>       Bytes received: 288.73MB
>       Bytes sent: 324.40MB
>       Packets received: 281664
>       Packets sent: 265715
>     lo:
>       Bytes received: 815.62kB
>       Bytes sent: 815.62kB
>       Packets received: 9664
>       Packets sent: 9664

After restarting the web services in each of the LXD/LXC containers the resource usage ramped up seeing an increase in the number of running processes and RAM utilization.

> on@dory:~$ lxc info u2004-onav-0 | grep Resources -A 4
> Resources:
>   Processes: 4165
>   Memory usage:
>     Memory (current): 25.60GB
>     Memory (peak): 58.46GB

> on@dory:~$ lxc info u2004-onav-1 | grep Resources -A 4
> Resources:
>   Processes: 9813
>   Memory usage:
>     Memory (current): 47.34GB
>     Memory (peak): 64.00GB

> on@dory:~$ lxc info u2004-onav-2 | grep Resources -A 4
> Resources:
>   Processes: 1419
>   Memory usage:
>     Memory (current): 7.57GB
>     Memory (peak): 64.00GB

The dreaded OOM process launched and terminated random processes within the LXD/LXC containers. Looking at the Gunicorn FAQ. For some reason the web process kicks into over drive and uses up all its memory allocation (each container is permitted to access 64GB and swap space). 

One of the suggested solutions is to increase the memory allocation. This sounds great at first however this could cause issues with other operational containers to run into resource issues if we decide to over provision the Ocean Navigator web service containers.

Another issue we need to look into further is why u2004-onav-1 and u2004-onav-2 encountered **BlockingIOError: [Errno 11] Resource temporarily unavailable** events. We had already implemented `--worker-tmp-dir /dev/shm`

> **How do I avoid Gunicorn excessively blocking in os.fchmod?**
> The current heartbeat system involves calling os.fchmod on temporary file handlers and may block a worker for arbitrary time if the directory is on a disk-backed filesystem. For example, by default /tmp is not mounted as tmpfs in Ubuntu; in AWS an EBS root instance volume may sometimes hang for half a minute and during this time Gunicorn workers may completely block in os.fchmod. os.fchmod may introduce extra delays if the disk gets full. Also Gunicorn may refuse to start if it can’t create the files when the disk is full.


> **Does Gunicorn suffer from the thundering herd problem?**
> The thundering herd problem occurs when many sleeping request handlers, which may be either threads or processes, wake up at the same time to handle a new request. Since only one handler will receive the request, the others will have been awakened for no reason, wasting CPU cycles. At this time, Gunicorn does not implement any IPC solution for coordinating between worker processes. You may experience high load due to this problem when using many workers or threads. However a work has been started to remove this issue.

![image](https://user-images.githubusercontent.com/44408505/101025735-921d9480-3550-11eb-9522-efce8ea77e3a.png)

**Comment by dwayne-hart** [comment]
To see how the LXD/LXC respond. I have updated the NGINX configuration to remove u2004-onav-2 from the web cluster definition, stopped the u2004-onav-2 container, and reallocated the RAM it was using to the other two remaining web cluster containers.

So both u2004-onav-0 and u2004-onav-1 containers are using 96GB of RAM.

```
on@dory:~$ lxc config set u2004-onav-0 limits.memory 96GB
on@dory:~$ lxc config set u2004-onav-1 limits.memory 96GB
```

**Comment by dwayne-hart** [comment]
This morning we found that the public facing Ocean Navigator web services were offline. Looking at the logging information we see that the containers are not able to start a new thread and that the software encountered a BlockingIOError.

> [2020-11-23 15:31:18 +0000] [18170] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
>     worker.init_process()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
>     super().init_process()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/base.py", line 140, in init_process
>     self.run()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 203, in run
>     callback(key.fileobj)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 124, in accept
>     self.enqueue_req(conn)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 114, in enqueue_req
>     fs = self.tpool.submit(self.handle, conn)
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
>     self._adjust_thread_count()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
>     t.start()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 54, in sentry_start
>     return old_start(self, *a, **kw)  # type: ignore
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/threading.py", line 846, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> [2020-11-23 15:31:18 +0000] [18170] [INFO] Worker exiting (pid: 18170)
> [2020-11-23 15:31:19 +0000] [785] [INFO] Unhandled exception in main loop
> Traceback (most recent call last):
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 211, in run
>     self.manage_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
>     self.spawn_workers()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
>     self.spawn_worker()
>   File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 567, in spawn_worker
>     pid = os.fork()
> BlockingIOError: [Errno 11] Resource temporarily unavailable
> [2020-11-23 15:31:19 +0000] [815] [INFO] Worker exiting (pid: 815)
> [2020-11-23 15:31:19 +0000] [811] [INFO] Worker exiting (pid: 811)
> [2020-11-23 15:31:19 +0000] [806] [INFO] Worker exiting (pid: 806)
> [2020-11-23 15:31:19 +0000] [813] [INFO] Worker exiting (pid: 813)
> [2020-11-23 15:31:19 +0000] [819] [INFO] Worker exiting (pid: 819)
> [2020-11-23 15:31:19 +0000] [821] [INFO] Worker exiting (pid: 821)
> [2020-11-23 15:31:19 +0000] [825] [INFO] Worker exiting (pid: 825)
> [2020-11-23 15:31:19 +0000] [827] [INFO] Worker exiting (pid: 827)
> [2020-11-23 15:31:19 +0000] [817] [INFO] Worker exiting (pid: 817)
> [2020-11-23 15:31:19 +0000] [803] [INFO] Worker exiting (pid: 803)
> [2020-11-23 15:31:19 +0000] [16156] [INFO] Worker exiting (pid: 16156)
> [2020-11-23 15:31:19 +0000] [823] [INFO] Worker exiting (pid: 823)

At this time I have updated the runserver.sh script to remove the `--worker-tmp-dir` option.

Originally:
```
gunicorn -w $((NUMBER_WORKERS)) --threads $((WORKER_THREADS)) --worker-class=gthread --worker-tmp-dir /dev/shm -t 300 --graceful-timeout 300 --preload -b 0.0.0.0:$((PORT)) --reload "oceannavigator:create_app()" $2
```
changed to:
```
gunicorn -w $((NUMBER_WORKERS)) --threads $((WORKER_THREADS)) --worker-class=gthread -t 300 --graceful-timeout 300 --preload -b 0.0.0.0:$((PORT)) --reload "oceannavigator:create_app()" $2
```

I then launched the script in order to restore the Ocean Navigator web services. Also, I had a quick look to see what the two containers memory resources had maxed out too.

![image](https://user-images.githubusercontent.com/44408505/101353092-a1148780-386d-11eb-8155-ea796a338510.png)

If this issue occurs again. I am planning to remove the `--threads $((WORKER_THREADS)) --worker-class=gthread` definition` option in order to reduce the number of active processes.

**Comment by dwayne-hart** [comment]
The issue occurred again today and I removed the gthread options. Things appear to be more stable but every now and then new requests can not be auctioned when all the workers are engaged in other user tasks.

**Comment by dwayne-hart** [comment]
Due to the slowness and connectivity issues when interacting with the Ocean Navigator. I went back to enabling worker threads in the `runserver.sh` script. This time I was more conservative in  the number of threads that I allowed.

Using the _**(2 x nproc)+1**_ formula for determining the number of workers to launch. I constrained the number of worker threads each worker could create to _**5**_ instead of the gunicorn documentation recommendation of _**2 x number of workers**_.

I then setup a simple `watch -n5 "lxc info u2004-onav-0 | grep -A5 Resources: ; lxc info u2004-onav-1 | grep -A5 Resources: ; lxc info u2004-staging | grep -A5 Resources:"` command to provide information pertaining to the three containers RAM  usage.

The two production containers are no where near the peaks that they were initially encountering causing the system to terminate random gunicorn process via OOM or gunicorn reporting that it could not create a thread process. 

![image](https://user-images.githubusercontent.com/44408505/101918456-f5887180-3ba3-11eb-9f32-bb564132baec.png)

**Comment by douglatornell** [comment]
Looks like exceptions from gunicorn have settled down in the past 24 hours, so I think you're headed in a promising direction...
https://sentry.io/organizations/dfo-ocean-navigator/issues/?groupStatsPeriod=24h&project=5511557&query=logger%3Agunicorn.error&statsPeriod=14d

**Comment by dwayne-hart** [comment]
The memory usage of the three containers has been steady.

![image](https://user-images.githubusercontent.com/44408505/102093625-f0bdfa80-3dfb-11eb-9377-f5773ec8b850.png)

The rule of _*# of workers = (nproc  x 2)+1 <= 13*_ and the number of threads being fixed at _*5*_ has certainly helped matters. Now to cement this change into the *runserver.sh* script.

**Comment by JustinElms** [comment]
No longer using gunicorn - does not appear to be affecting the current iteration of the Navigator.
