### ISSUE TITLE
Does the "data" argument in api_v1_0.plot_v1_0() make any sense?

### ISSUE THREAD

**Issue by douglatornell** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#773]
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/ea00877de046c1de02c598d03642232799f6ba50/routes/api_v1_0.py#L515-L517
looks like it is intended for use by Python code to get the data underlying the a plot, but there is no way for such a call to provide a `request` object outside of the app running, is there? So, what is the purpose of this code?

https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/ea00877de046c1de02c598d03642232799f6ba50/routes/api_v1_0.py#L532-L539
can't be reached due to L515-L517. That's a good thing because it is bugged by it's use of `resp` rather than `response`. If I am reading this bit correctly in context, if it worked, it would return the PNG image as JSON. What is the purpose of that?

I think that both of these fragments of code are hold-overs from history that no longer have purpose and should be deleted, but perhaps there's something that I am missing. @htmlboss can you shed any light on this?

**Comment by JustinElms** [comment]
The "data" argument was removed when migrating to FastAPI.
