### ISSUE TITLE
Google SEO not complete 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#8]
the Ocean Navigator is not very discoverable by Google at the moment. SEO should be completed

**Comment by Jeffreydaw** [comment]
current issues 
https://try.powermapper.com/Reports/520fa488-db52-4618-8412-6805e1e3b37f/report/res/2.view.htm

https://try.powermapper.com/demo/ViewScan/520fa488-db52-4618-8412-6805e1e3b37f

**Comment by htmlboss** [comment]
#225
