### ISSUE TITLE
Empty plot axis appearing in 2 places when ETOPO1 Topography is selected as Basemap (Staging site)

### ISSUE THREAD

**Issue by BaruaSourav** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#818]
When first time loaded and the basemap has been set to the default basemap **ETOPO1 Topography**, the global map loads with two empty plot axis rendered with the basemap on the Europe region. 

**To Reproduce**
It appears on the staging site. When someone lands on the first global view, it loads with  **ETOPO1 Topography** selected as basemap. If you drag above Europe, there will be two empty plot axis appearing on the map. 

**Expected behavior**
The map should be displayed without any axis appearing over it.

**Screenshots**
![image](https://user-images.githubusercontent.com/12777798/109062746-e0ab7c80-76c2-11eb-985f-40dba7a6856c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280

**Additional context**
The backend is may be binding those plot with the tile image.

**Comment by BaruaSourav** [comment]
The axis image appears for below two specific calls to the backend.

[Call 1 that returns axis with the map](http://navigator.oceansdata.ca:89/api/v1.0/tiles/bath/EPSG:3857/4/9/5.png)
[Call 2 that returns axis with the map](http://navigator.oceansdata.ca:89/api/v1.0/tiles/bath/EPSG:3857/4/9/4.png)

**Comment by jmunroe** [comment]
Call 1 should produce:

![image](https://user-images.githubusercontent.com/6181563/109167567-e39e7f80-774b-11eb-95ea-9fd86ea380bb.png)

This is what the [production side](https://navigator.oceansdata.ca/api/v1.0/tiles/bath/EPSG:3857/4/9/5.png) currently gives.

I suppose there was an intermittent error of creating this tile on the staging site and now that tile is cached on the server.  As mentioned in the meeting yesterday, I've seen this kind of behaviour before (and I think at the same location!).  

@BaruaSourav  Does this issue occur in your dev container?

**Comment by BaruaSourav** [comment]
Just checked on the dev container and it returns - 
![image](https://user-images.githubusercontent.com/12777798/109190605-d1363d00-776f-11eb-9b47-fdb9df091302.png)

So it is some error that is happened and cached at the staging server. 

Do we have any idea where we can look into regarding this tile having those axis? I guess, the **/tiles** call to the API should be checked to find the reason behind this.

**Comment by BaruaSourav** [comment]
Looks like the staging site is fixed when it is rebuilt and this issue is not appearing anymore. 





> The axis image appears for below two specific calls to the backend.
> 
> [Call 1 that returns axis with the map](http://navigator.oceansdata.ca:89/api/v1.0/tiles/bath/EPSG:3857/4/9/5.png)
> [Call 2 that returns axis with the map](http://navigator.oceansdata.ca:89/api/v1.0/tiles/bath/EPSG:3857/4/9/4.png)

These calls doesn't bring up those axis anymore and I think we can close this issue.
