### ISSUE TITLE
Cannot Subset NetCDF from Predefined Areas

### ISSUE THREAD

**Issue by JustinElms** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#864]
**Describe the bug**
Users are not able to save a NetCDF subset of a predefined area. Nothing seems to happen when clicking the Save button once the variables, time, and output format are selected and the Navigator front end does not appear to make a call to the back end. It looks like the name of the predefined area is passed to the calculateAreaBoundingBox method in AreaWindow.jsx but it expects an object with polygons. This yields and error and prevents the Navigator from proceeding.

**To Reproduce**
Select any of the predefined areas listed in the Area menu. When the Area Window opens select any variable, time and output format then click Save. Nothing happens.

**Expected behavior**
After some time a NetCDF file should download.

**Screenshots**
![nc_error](https://user-images.githubusercontent.com/79917349/126536743-bc3af959-2dc6-4481-89d7-980af160b8e3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 91.0.4472.164

**Comment by JustinElms** [comment]
It looks like the generate API script function for areas is also broken. I don't think this is limited to the predefined areas.

**Comment by BaruaSourav** [comment]
Just checked the API script generation (user-drawn polygon and pre-defined areas) function for the Staging, have been waiting for the server to respond for a long time now. Tried the link separately on the browser, no good as well. I remember checking them when pushing the PR related to it, it was working then. It might be the staging env responding slowly.
