### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#887]
We are getting an error related to git LFS when running the Project Ocean Navigator create CLASS4 pickle on Jenkins:

```
12:10:07 Cloning into 'Ocean-Data-Map-Project'...
12:10:30 Downloading kml/area/SAR_Areas.kml (118 MB)
12:10:43 Error downloading object: kml/area/SAR_Areas.kml (218a9d2): Smudge error: Error downloading kml/area/SAR_Areas.kml (218a9d2371ebb1e5e5b56e4d544b58d6ddf914568603faa0fba361e2dc4480ce): batch response: Fatal error: Server error: https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project.git/info/lfs/objects/batch from HTTP 502
12:10:43 
12:10:43 Errors logged to /var/jenkins_home/sandbox-pickle/Ocean-Data-Map-Project/.git/lfs/logs/20210810T161043.819536906.log
12:10:43 Use `git lfs logs last` to view the log.
12:10:43 error: external filter 'git-lfs filter-process' failed
12:10:43 fatal: kml/area/SAR_Areas.kml: smudge filter lfs failed
```

I assume this is due to insufficient storage available on GitHub for LFS:

```
(navigator-env) jmunroe@ubuntu-focal:~/Ocean-Data-Map-Project/kml/area$ git lfs checkout
Skipped checkout for "kml/area/SAR_Areas.kml", content not local. Use fetch to download.                                    
(navigator-env) jmunroe@ubuntu-focal:~/Ocean-Data-Map-Project/kml/area$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project.git/info/lfs'
```

I know this issue was brought up in the tech meeting last week. Documenting it here for future reference.

**Comment by jmunroe** [comment]
GitHub provides 1GB of free storage and 1GB a month of free bandwidth. [link](https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage)

The password I have on record for the GitHub account "Ocean-Navigator" is no longer valid.  Could someone (@dwayne-hart ?) report on 
- the amount of storage used,
- the amount of free bandwidth used this month,
- and when the usage resets for the next month?

I think the only file we have in git lfs is `kml/area/SAR_Areas.kml` that looks like it was added by @JustinElms (Apr-2021). Was it necessary to use lfs?  Alternatively, should we be treating all of these kml files like "data" and storing them outside of this repository (and put them somewhere like `/data/kml` instead?)

**Comment by JustinElms** [comment]
`SAR_Areas.kml` was just big enough that we had to use LFS. I believe it's around 120 mb and has 40 individual areas in it. if we need the LFS space it could be broken up into a few smaller files (possibly Atlantic, Pacific, and Arctic) and added directly to the repo or we could down sample the boundaries of the areas. We should check with CCG before modifying it in either case.

**Comment by jmunroe** [comment]
Since the data we were storing in the `/kml` subdirectory was static, we can sidestep this LFS issue by storing the data in `/data/kml` instead.  This change in the configuration was accomplished in PR #889.
