### ISSUE TITLE
Error when changing variable in Virtual Mooring tab

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#912]
After selecting Virtual Mooring tab and attempting to change the variable I am getting a white screen and no result. This occurred consistently. 

![image](https://user-images.githubusercontent.com/30048431/134600006-af2e4719-a0ca-4ddb-b0f6-8727b1aef626.png)

Result of selecting temperature variable:
![image](https://user-images.githubusercontent.com/30048431/134600080-806395ef-bc5f-4981-9895-5e1b97c1b239.png)

**Comment by JustinElms** [comment]
This should be fixed with PR #903 which will make its way to production with the next release.
