### ISSUE TITLE
missing depth drop down

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#923]
Several 3D datasets do not have a 'depth' drop down (several CMEMS datasets including dataset 19)

![image](https://user-images.githubusercontent.com/30048431/142049769-2025fe61-aa76-4028-b89f-1c8b6c76051e.png)

Possibly associated with this issue is another:
Dataset 15.CMEMS... has a depth variable but only has '0' or 'Bottom' in the dropdown.

**Comment by JustinElms** [comment]
Not confirmed yet, but I think this might be related to PR #880.  It looks like the Navigator only queries depths for first variable when changing datasets. If this variable is 2D then the Navigator won't add the 'Depth' dropdown to the global view for that dataset.

**Comment by JustinElms** [comment]
Here's a quick list of the number of depth levels available for each variable for reference: https://docs.google.com/document/d/1OaNT8-kALrNUIQufLTwgQTWsOK0369FpzAfmdqgAWHE/edit?usp=sharing
