### ISSUE TITLE
Missing Dataset help [?]

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#938]
With the latest release the Dataset [?] is missing from the front end. 

Pre-release
![pre-release](https://user-images.githubusercontent.com/30048431/148578157-647a3a16-a5ca-4ff6-a6b3-dd41278ead09.jpg)

post release (image of production on CHIA)
![post release](https://user-images.githubusercontent.com/30048431/148578205-0b9e51cc-ed83-4b0b-84c3-967cde985b94.png)

**Comment by htmlboss** [comment]
oops! forgot to add that back. I'll take a look this week.

**Comment by JustinElms** [comment]
Fixed with #940
