### ISSUE TITLE
`DATASET_DEFAULTS` time values break dataset comparison

### ISSUE THREAD

**Issue by JustinElms** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#950]
**Describe the bug**
This issue is related to the defaults.js file added in #926. This file includes a `DATASET_DEFAULTS` (in defaults.js) parameter which specifies the default options to use when the Navigator is started. Among these options we specify default values time = -1 and starttime = -2 but one the DatasetSelector retrieve the timestamps available for the dataset these values are replaced with actual timestamps. The dataset used for comparisons, `dataset_1`, also uses the defaults listed in this file, however, the time and starttime values do not get updated. So when 'Show Comparison' is selected, the query is sent with -1 instead of a timestamp which prevents any data from being queried. 

**To Reproduce**
Click 'Show Comparison' at any point when using the Navigator. The API query will fail in any scenario since the dataset time doesn't get updated.  This prevents plotting of comparison data, and tile generation in the right map window when visible. 

**Expected behavior**
The user should see the comparison data requested. 

**Screenshots**

**Additional context**
I also noticed a bunch of queries with timestamp = -1 getting sent when I start the Navigator. My guess is that the Navigator is making these requests before the timestamp gets updated to a real value.

**Comment by htmlboss** [comment]
>Additional context
I also noticed a bunch of queries with timestamp = -1 getting sent when I start the Navigator. My guess is that the Navigator is making these requests before the timestamp gets updated to a real value.

You're correct with that. To solve that my thinking is to simply add an optional `latest` argument to the `/timestamps` endpoint so we can query that when the Navigator first loads. Also, it's a nice helper method without having to load all the timestamps. I don't think that's required to resolve this issue, but if I remember I can add that too.
