### ISSUE TITLE
Dataset comparison GO button doesn't request data

### ISSUE THREAD

**Issue by JustinElms** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#951]
**Describe the bug**
The Go button isn't sending plot requests when 'Show Comparison' is selected in the line/area windows. 

**To Reproduce**
Open a point/line/area plot and click the 'Show Comparison' checkbox. A second panel will appear for the right map/comparison data but clicking go doesn't send a request for a new plot. 

**Expected behavior**
A new comparison plot should be generated.

**Comment by htmlboss** [comment]
Works for me on the staging site haha (https://staging.oceansdata.ca/public/). It gives the appearance it's doing nothing but it takes a sec to load the image. I think #952 and #954 fixed it.

![image](https://user-images.githubusercontent.com/5572045/151438976-509f0a0c-e945-4432-b08d-a9278587579e.png)

**Comment by JustinElms** [comment]
@htmlboss Oh awesome! Didn't notice that it was working in the line window. I can't seem to get it to work for the area window though.
