### ISSUE TITLE
track user count

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#99]
we should start tracking the number f requests our server is getting to get an Idea of how many users are using the system and how intensely.  it may be good to log server load as well.

**Comment by Jeffreydaw** [comment]
look into using google analytics
http://www.google.com/analytics/analytics/capabilities/
https://web-design-weekly.com/2016/07/08/adding-google-analytics-react-application/

**Comment by NoahGallant-MUN** [comment]
This has been completed - Website visits and plot creations are tracked
